### ISSUE TITLE
System.register is not supported by webpack

### ISSUE THREAD

**Issue by Shofol** [ng-packagr/ng-packagr#1118]
## Type of Issue
The mismatch between the main application's `tsconfig `module and library's `tsconfig  `module
`
[x] Bug Report
```

## Description

_A bug: please describe the error that you encountered_
I needed to change my `tsconfig.lib.json` file because an authentication file was missing when the module was set to `es2015`. The build error was- 
```
BUILD ERROR
Could not resolve './ngsso' from dist\services-shared-lib\esm2015\lib\security\ngoauth\ngsso.service.js
Error: Could not resolve './ngsso' from dist\services-shared-lib\esm2015\lib\security\ngoauth\ngsso.service.js
    at error (E:\Projects\ababil-ng-web\node_modules\rollup\dist\rollup.js:3460:30)
    at E:\Projects\ababil-ng-web\node_modules\rollup\dist\rollup.js:21850:25
    at <anonymous>
```
But, when I set the module to `system` then it got built. I installed that in my main project but it showed warning on `npm start`-

```
WARNING in ./node_modules/services-shared-lib/fesm5/services-shared-lib.js
System.register is not supported by webpack.
```
And, at last I got this error in the browser- 

```
core.js:1673 ERROR Error: Uncaught (in promise): TypeError: (void 0) is not a function
TypeError: (void 0) is not a function
    at Object../projects/cis-shared-lib/node_modules/services-shared-lib/fesm5/services-shared-lib.js (services-shared-lib.js:1)
    at __webpack_require__ (bootstrap:81)
    at Object../projects/cis-shared-lib/src/lib/cis.service.ts (cis.api.endpoints.ts:62)
    at __webpack_require__ (bootstrap:81)
    at Object../projects/cis-shared-lib/src/lib/cis-shared-lib.component.ts (ababil-modules-cis-cis-module.js:134)
    at __webpack_require__ (bootstrap:81)
    at Object../projects/cis-shared-lib/src/lib/cis-shared-lib.module.ts (cis-shared-lib.component.ts:12)
    at __webpack_require__ (bootstrap:81)
    at Object../src/app/ababil-modules/cis/cis.module.ts (cis.inactive.customer.component.ts:22)
    at __webpack_require__ (bootstrap:81)
    at Object../projects/cis-shared-lib/node_modules/services-shared-lib/fesm5/services-shared-lib.js (services-shared-lib.js:1)
    at __webpack_require__ (bootstrap:81)
    at Object../projects/cis-shared-lib/src/lib/cis.service.ts (cis.api.endpoints.ts:62)
    at __webpack_require__ (bootstrap:81)
    at Object../projects/cis-shared-lib/src/lib/cis-shared-lib.component.ts (ababil-modules-cis-cis-module.js:134)
    at __webpack_require__ (bootstrap:81)
    at Object../projects/cis-shared-lib/src/lib/cis-shared-lib.module.ts (cis-shared-lib.component.ts:12)
    at __webpack_require__ (bootstrap:81)
    at Object../src/app/ababil-modules/cis/cis.module.ts (cis.inactive.customer.component.ts:22)
    at __webpack_require__ (bootstrap:81)
    at resolvePromise (zone.js:814)
    at resolvePromise (zone.js:771)
    at zone.js:873
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:3815)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
```

#### How To Reproduce

_A bug: please include instructions how to reproduce. Issues without reproduction are likely to receive no feedback._
Change the `tsconfig.lib.json` file's module to `system`
_Can you reproduce the error in the integration tests in ng-packagr?_
_If possible, take a look at the [`integration/samples`](./integration/samples) and try to break one of these builds!_

_Is the error you faced in an application importing the library_
_Try to break the Angular CLI app in [`integration/consumers/ng-cli`](./integration/consumers/ng-cli)!_


#### Expected Behaviour

_A bug: please describe what behaviour or result you expected_

_A feature: do you have a first draft or an idea how to implement?_


#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 4.3.0
@angular-devkit/architect          0.7.5
@angular-devkit/build-angular      0.7.5
@angular-devkit/build-ng-packagr   0.8.5
@angular-devkit/build-optimizer    0.7.5
@angular-devkit/build-webpack      0.7.5
@angular-devkit/core               0.7.5
@angular-devkit/schematics         0.8.1
@angular/cdk                       6.4.7
@angular/cli                       6.2.1
@angular/material                  6.4.7
typescript: 2.7.2
rxjs: 6.2.2
node: 8.11.3
npm/yarn: 6.4.0
```
_Please include all version numbers that might be relevant, e.g. third-party libraries_
webpack: 4.9.2

**Comment by alan-agius4** [comment]
I am sorry but **system** modules are not supported as they don't conform with Angular Package Format.

**Comment by Shofol** [comment]
Thank you for the clarification. I had a js file which I think written on old ES version. When I build the package then the service file can't get that js file. Again the build error- 

```
BUILD ERROR
Could not resolve './ngsso' from dist\services-shared-lib\esm2015\lib\security\ngoauth\ngsso.service.js
Error: Could not resolve './ngsso' from dist\services-shared-lib\esm2015\lib\security\ngoauth\ngsso.service.js
    at error (E:\Projects\ababil-ng-web\node_modules\rollup\dist\rollup.js:3460:30)
    at E:\Projects\ababil-ng-web\node_modules\rollup\dist\rollup.js:21850:25
    at <anonymous>
```
[ngoauth.zip](https://github.com/ng-packagr/ng-packagr/files/2481368/ngoauth.zip)

**Comment by alan-agius4** [comment]
You cannot include JS files unless they are npm modules
