### ISSUE TITLE
Cannot find module '@angular/compiler-cli' (already tried the suggested solutions)

### ISSUE THREAD

**Issue by avifatal** [ng-packagr/ng-packagr#1141]
Hi,
Just cloned the ng-packaged and try to run `ng-packagr -p my-lib/package.json` and the following error accured.  

Already tried with: https://stackoverflow.com/a/43931987

```
$ ng-packagr -p my-lib/package.json
module.js:549
    throw err;
    ^

Error: Cannot find module '@angular/compiler-cli'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Avi\AppData\Roaming\npm\node_modules\ng-packagr\lib\ts\tsconfig.js:3:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```
Thanks

**Comment by stones** [comment]
I had to install `@angular/compiler-cli` not just the cli.

**Comment by kumaresan-subramani** [comment]
i have tried but no improvement
