### ISSUE TITLE
Examples for Moment.js do not work

### ISSUE THREAD

**Issue by cbacko01** [ng-packagr/ng-packagr#1149]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

The examples for getting Moment.js included as a dependency in the package do not appear to work. The examples used are in #290 and #163 (which are also referenced in #129). The solutions provided result in the following error: 

```
Module not found: Error: Can't resolve 'moment' in <project-path>/fesm5
```

In case I'm misinterpreting the provided solutions or missing a step, I've created a repository (below) to show concretely how I'm attempting to get this working.

#### How To Reproduce

I've created [this basic example project](https://github.com/cbacko01/ng-packagr-moment) (following [this guide](https://blog.angularindepth.com/creating-a-library-in-angular-6-87799552e7e5)) that reproduces the issue. To reproduce using the project:

```
npm i
(cd projects/package-test-ng7/ && npm i)
ng build package-test-ng7
# Project should build successfully
ng serve
# Project fails to compile, with aforementioned error.
```

#### Expected Behaviour

The project including the package should compile and run without error, without needing to install `moment` in the project using the package. 

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            4.4.0
@angular/compiler:     7.0.4
rollup:                0.66.6
tsickle:               0.34.0
typescript:            3.1.6

moment:    2.22.2
```

Thank you very much for your help.

**Comment by carnival187** [comment]
Resolve liki this for me : 
everytime you import moment, do like this :
`
    import {_moment} from "moment; 
    const moment = _moment`

and use the `moment' variable

**Comment by cbacko01** [comment]
@carnival187 I'm afraid that doesn't work. If I replace my import statement(s) with 

```
import { * as _moment } from "moment"; const moment = _moment;
```

And try to build the package, I get the following error: 

```
BUILD ERROR
projects/package-test-ng7/src/lib/foo/foo.component.ts(3,10): error TS1003: Identifierexpected.
projects/package-test-ng7/src/lib/foo/foo.component.ts(3,15): error TS1005: ';' expected.
projects/package-test-ng7/src/lib/foo/foo.component.ts(3,23): error TS1128: Declaration or statement expected.
projects/package-test-ng7/src/lib/foo/foo.component.ts(3,30): error TS1005: ';' expected.

Error: projects/package-test-ng7/src/lib/foo/foo.component.ts(3,10): error TS1003: Identifier expected.
projects/package-test-ng7/src/lib/foo/foo.component.ts(3,15): error TS1005: ';' expected.
projects/package-test-ng7/src/lib/foo/foo.component.ts(3,23): error TS1128: Declaration or statement expected.
projects/package-test-ng7/src/lib/foo/foo.component.ts(3,30): error TS1005: ';' expected.

    at Object.<anonymous> (/Users/backocr1/Desktop/package-test-ng7/node_modules/ng-packagr/lib/ngc/compile-source-files.js:40:68)
    at Generator.next (<anonymous>)
    at /Users/backocr1/Desktop/package-test-ng7/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/backocr1/Desktop/package-test-ng7/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/Users/backocr1/Desktop/package-test-ng7/node_modules/ng-packagr/lib/ngc/compile-source-files.js:17:12)
    at Object.<anonymous> (/Users/backocr1/Desktop/package-test-ng7/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:31:32)
    at Generator.next (<anonymous>)
    at /Users/backocr1/Desktop/package-test-ng7/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)

projects/package-test-ng7/src/lib/foo/foo.component.ts(3,10): error TS1003: Identifierexpected.
projects/package-test-ng7/src/lib/foo/foo.component.ts(3,15): error TS1005: ';' expected.
projects/package-test-ng7/src/lib/foo/foo.component.ts(3,23): error TS1128: Declaration or statement expected.
projects/package-test-ng7/src/lib/foo/foo.component.ts(3,30): error TS1005: ';' expected.

Error: projects/package-test-ng7/src/lib/foo/foo.component.ts(3,10): error TS1003: Identifier expected.
projects/package-test-ng7/src/lib/foo/foo.component.ts(3,15): error TS1005: ';' expected.
projects/package-test-ng7/src/lib/foo/foo.component.ts(3,23): error TS1128: Declaration or statement expected.
projects/package-test-ng7/src/lib/foo/foo.component.ts(3,30): error TS1005: ';' expected.

    at Object.<anonymous> (/Users/backocr1/Desktop/package-test-ng7/node_modules/ng-packagr/lib/ngc/compile-source-files.js:40:68)
    at Generator.next (<anonymous>)
    at /Users/backocr1/Desktop/package-test-ng7/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/backocr1/Desktop/package-test-ng7/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/Users/backocr1/Desktop/package-test-ng7/node_modules/ng-packagr/lib/ngc/compile-source-files.js:17:12)
    at Object.<anonymous> (/Users/backocr1/Desktop/package-test-ng7/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:31:32)
    at Generator.next (<anonymous>)
    at /Users/backocr1/Desktop/package-test-ng7/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
```

If you could provide a working repo, I'd be happy to try it out to verify your fix works.

**Comment by JoostK** [comment]
@cbacko01 There's a syntax error in that example, should be:

```typescript
import * as _moment from "moment"; const moment = _moment;
```

**Comment by cbacko01** [comment]
@JoostK Per the documentation (#290 and #163), my original code was:

```
import * as momentNs from 'moment';
const moment = momentNs;
```

The package would compile, but the project would not. Your variation appears to result in the same issue as the original code: 

```
ERROR in ./dist/package-test-ng7/fesm5/package-test-ng7.js
Module not found: Error: Can't resolve 'moment' in '/Users/backocr1/Desktop/package-test-ng7/dist/package-test-ng7/fesm5'
```

But if you can point me to a working repository, I'd love to give it a try.

**Comment by JoostK** [comment]
@cbacko01 Haha well I wrote that documentation and that has worked in the past just fine.

Do you have moment installed in your node_modules properly? I don't know what's going on really.

**Comment by alan-agius4** [comment]
Moment doesn’t seem to be required nor installed in the application
https://github.com/cbacko01/ng-packagr-moment/blob/master/package.json

**Comment by cbacko01** [comment]
@JoostK Ah, sorry, I didn't recognize your username >.<

The project has 2 `package.json` files: one for the library I'm trying to package, and one for the project I'm trying to run it in. I have `moment` specified as a `dependency` for the library:

```
{
  "$schema": "../../node_modules/ng-packagr/package.schema.json",
  "name": "package-test-ng7",
  "version": "0.0.1",
  "peerDependencies": {
    "@angular/common": "^7.0.0",
    "@angular/core": "^7.0.0"
  },
  "dependencies": {
    "i": "^0.3.6",
    "moment": "^2.22.2",
    "npm": "^6.4.1"
  }
}
```

I've intentionally left moment uninstalled in my project, which doesn't use `moment` directly; `moment` is only required for the `FooComponent` which is exported by my library. `FooComponent` is then imported from the library and used in the project. My goal is to distribute my library without requiring that consumer projects have `moment` installed.

**Comment by alan-agius4** [comment]
Hi, Moment doesn’t seem to be required nor installed in the application
https://github.com/cbacko01/ng-packagr-moment/blob/master/package.json

In your component library you are using moment as a dependency which is
highly discouraged. See
https://github.com/ng-packagr/ng-packagr/blob/master/docs/dependencies.md
 why this is not a good practice.

Sorry for being brief but I am answering from a mob.

**Comment by cbacko01** [comment]
@alan-agius4 Thanks for your response! 

1. I've read the best practice documentation you linked. However, I have a use case where I need to use `moment` as a dependency. 
2. According to #290 and #163, using `moment` as a dependency is supported. If this is not the case, the issues are misleading and should be updated.
3. It wasn't clear that I needed to install `moment` in the main application to test using `ng serve`. The alternative seems to be to install the generated package `.tgz` as a dependency for my project, and this seems to allow me to use `moment` in the package without installing it in the project. I think this solves my issue. 
4. I expected the command `ng build package-test-ng7` to behave just like referencing the `.tgz` as a dependency would have. Perhaps I should have known better, but it would be nice if this were more clearly documented.
5. I'd be happy to generate some updated documentation. Is there a process for submitting documentation contributions?

**Comment by benjamincharity** [comment]
@cbacko01 	not sure if this is exactly what you're hitting, but to get bundled dependencies working we had to define `umdModuleIds` and `whitelistedNonPeerDependencies`:

In our `package.json`:
```
  ...
  "ngPackage": {
    "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
    "workingDirectory": "../.ng_build",
    "lib": {
      "entryFile": "src/public-api.ts",
      "umdModuleIds": {
        "@angular/cdk": "ng.cdk",
        "@terminus/ngx-tools": "terminus.ngxTools",
        "@terminus/ngx-tools/coercion": "terminus.ngxTools.coercion",
        "@terminus/ngx-tools/regex": "terminus.ngxTools.regex",
        "@terminus/ngx-tools/keycodes": "terminus.ngxTools.keycodes",
        "date-fns": "dateFns",
        "ngx-perfect-scrollbar": "ngxPerfectScrollbar",
        "text-mask-core/dist/textMaskCore": "textMaskCore",
        "text-mask-addons/dist/createNumberMask": "createNumberMask",
        "text-mask-addons/dist/createAutoCorrectedDatePipe": "createAutoCorrectedDatePipe"
      },
      "comments": "none"
    },
    "whitelistedNonPeerDependencies": [
      "@angular/cdk",
      "ngx-perfect-scrollbar",
      "text-mask-addons",
      "text-mask-core"
    ],
    "dest": "../dist/terminus-ui"
  }
  ...
```

In this case ngx-perfect-scrollbar and the text mask libraries are bundled.

**Comment by cbacko01** [comment]
I have updated my linked git repo ([here](https://github.com/cbacko01/ng-packagr-moment)) with the changes I mentioned in my earlier post. In particular, I am able to get the project to compile by completely building the library as a .tgz and including the built library as a dependency in my project. I'm not quite sure that this is the _intended_ or best solution to this issue. In that example, I _do_ set the `umdModuleIds` and `whitelistedNonPeerDependencies` roughly how @benjamincharity described.

**Comment by alan-agius4** [comment]
Closing as this issue is stale, if the problem persists please file a new issue with a reproduction.
