### ISSUE TITLE
While using ng-packagr to generate angular package, it throws `Object.getJSDocTags` error

### ISSUE THREAD

**Issue by kumaresan-subramani** [ng-packagr/ng-packagr#1207]
## Type of Issue

```
[x] Bug Report
```

## Description

_A bug: _

### while using ng-packgr to generate angular package it throws following error.

`> @syncfusion/ej2-angular-buttons@17.1.1 packagr D:\workspace\components\ej2-button-components\third-party\angular
> ng-packagr -p ng-package.json && gulp tslib-resolve && gulp npmrc-changelog-injection

Building Angular library
Generating bundle for @syncfusion/ej2-angular-buttons
Cleaning bundle build directory
Processing assets
Running ngc
Compiling to FESM15
Compiling to FESM5

BUILD ERROR
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at Object.getJSDocTags (D:\workspace\components\ej2-button-components\third-party\angular\node_modules\typescript\lib\typescript.js:13197:22)
    at getJSDocTypeParameterDeclarations (D:\workspace\components\ej2-button-components\third-party\angular\node_modules\typescript\lib\typescript.js:11650:30)
    at Object.getEffectiveTypeParameterDeclarations (D:\workspace\components\ej2-button-components\third-party\angular\node_modules\typescript\lib\typescript.js:11645:67)
    at checkClassLikeDeclaration (D:\workspace\components\ej2-button-components\third-party\angular\node_modules\typescript\lib\typescript.js:48734:36)
    at checkClassExpression (D:\workspace\components\ej2-button-components\third-party\angular\node_modules\typescript\lib\typescript.js:48710:13)
    at checkExpressionWorker (D:\workspace\components\ej2-button-components\third-party\angular\node_modules\typescript\lib\typescript.js:45678:28)
    at checkExpression (D:\workspace\components\ej2-button-components\third-party\angular\node_modules\typescript\lib\typescript.js:45609:42)
    at checkBinaryLikeExpression (D:\workspace\components\ej2-button-components\third-party\angular\node_modules\typescript\lib\typescript.js:45155:29)
    at checkBinaryExpression (D:\workspace\components\ej2-button-components\third-party\angular\node_modules\typescript\lib\typescript.js:45147:20)
    at checkExpressionWorker (D:\workspace\components\ej2-button-components\third-party\angular\node_modules\typescript\lib\typescript.js:45702:28)

npm ERR! code ELIFECYCLE
npm ERR! errno 111
npm ERR! @syncfusion/ej2-angular-buttons@17.1.1 packagr: `ng-packagr -p ng-package.json && gulp tslib-resolve && gulp npmrc-changelog-injection`
npm ERR! Exit status 111
npm ERR!
npm ERR! Failed at the @syncfusion/ej2-angular-buttons@17.1.1 packagr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kumaresan.subramani\AppData\Roaming\npm-cache\_logs\2019-02-04T04_19_15_625Z-debug.log`

#### Expected Behaviour

if i use typescript version 2.8.4 or 2.7.2, issue wont be reproduced. i don't know why. so please explain this to me?

### working fine
`"ng-packagr": "1.5.0",
  "tsickle": "0.34.0",
   "typescript": "^2.8.4",
    "uglify-js": "3.2.2"`

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 1.5.0
@angular/*: 4.10.0
typescript: 2.9.2
rxjs: x.y.z
node: 8.11.3
npm/yarn: 6.6.0
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by kumaresan-subramani** [comment]
Hi,
Please update to me regarding this? due to this my whole project got stopped

**Comment by JoostK** [comment]
@kumaresan-subramani Please be patient a bit. Based on the stacktrace, you are looking at a TypeScript bug. If you were to search the TypeScript repo for issues, you'd have quickly found https://github.com/Microsoft/TypeScript/issues/24963 among others. Please refer to that bug report for possible workarounds.

**Comment by kumaresan-subramani** [comment]
hi @JoostK , i have searched lot bro but i didn't get any solution. can you please suggest any solution?

**Comment by alan-agius4** [comment]
The solution would be to downgrade or upgrade typescript.

Upgrade is the suggested path of course.
