### ISSUE TITLE
BrowserslistError: Unknown version 8.2 of samsung

### ISSUE THREAD

**Issue by jamieathans** [ng-packagr/ng-packagr#1221]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

During a compile of my Angular library (monorepo using Angular CLI), the following build error occurs:

```
Building Angular Package
Building entry point 'common-lib'
Compiling TypeScript sources through ngc

BUILD ERROR
Unknown version 8.2 of samsung
BrowserslistError: Unknown version 8.2 of samsung
    at Function.select (/Users/jamie/Projects/whittles/whittles-web-ui/node_modules/autoprefixer/node_modules/browserslist/index.js:846:17)
    at /Users/jamie/Projects/whittles/whittles-web-ui/node_modules/autoprefixer/node_modules/browserslist/index.js:176:33
    at Array.reduce (<anonymous>)
    at resolve (/Users/jamie/Projects/whittles/whittles-web-ui/node_modules/autoprefixer/node_modules/browserslist/index.js:158:18)
    at browserslist (/Users/jamie/Projects/whittles/whittles-web-ui/node_modules/autoprefixer/node_modules/browserslist/index.js:278:16)
    at Browsers.parse (/Users/jamie/Projects/whittles/whittles-web-ui/node_modules/autoprefixer/lib/browsers.js:66:12)
    at new Browsers (/Users/jamie/Projects/whittles/whittles-web-ui/node_modules/autoprefixer/lib/browsers.js:48:26)
    at loadPrefixes (/Users/jamie/Projects/whittles/whittles-web-ui/node_modules/autoprefixer/lib/autoprefixer.js:85:20)
    at plugin (/Users/jamie/Projects/whittles/whittles-web-ui/node_modules/autoprefixer/lib/autoprefixer.js:96:20)
    at LazyResult.run (/Users/jamie/Projects/whittles/whittles-web-ui/node_modules/postcss/lib/lazy-result.js:295:14)
    at LazyResult.sync (/Users/jamie/Projects/whittles/whittles-web-ui/node_modules/postcss/lib/lazy-result.js:281:26)
    at LazyResult.warnings (/Users/jamie/Projects/whittles/whittles-web-ui/node_modules/postcss/lib/lazy-result.js:85:17)
    at StylesheetProcessor.process (/Users/jamie/Projects/whittles/whittles-web-ui/node_modules/ng-packagr/lib/ng-v5/entry-point/resources/stylesheet-processor.js:32:16)
    at Object.readResource (/Users/jamie/Projects/whittles/whittles-web-ui/node_modules/ng-packagr/lib/ts/cache-compiler-host.js:73:57)
    at TsCompilerAotCompilerTypeCheckHostAdapter.loadResource (/Users/jamie/Projects/whittles/whittles-web-ui/node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:481:37)
    at Object.get (/Users/jamie/Projects/whittles/whittles-web-ui/node_modules/@angular/compiler/bundles/compiler.umd.js:25582:94)

```

#### How To Reproduce

Upgrade from ng-packagr `4.7.0` to `4.7.1` (problem does **not** occur on `4.7.0`)

#### Expected Behaviour

Regular build without error.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 4.7.1
@angular/compiler: 7.2.5
rollup: 0.67.4
tsickle: 0.34.3
typescript: 3.2.4
rxjs: 6.4.0
rxjs-compat: 6.4.0
node: 10.15.1
npm: 6.4.1
```

**Comment by jamieathans** [comment]
Looks like this was an npm issue/bug.

After blowing away my `package-lock.json` and doing a fresh `npm i`, problem was resolved.
