### ISSUE TITLE
Invalid regular expression: /*/: Nothing to repeat

### ISSUE THREAD

**Issue by matheo** [ng-packagr/ng-packagr#1321]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Yesterday I upgraded my `matheo/angular` project to Angular `v8`, and today I realized I'm not able to build my library like in `v7`. I got this error:

```
$ yarn build datasource
yarn run v1.16.0
Building Angular Package
Building entry point '@matheo/datasource'
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Function.prototype.arguments not supported [0:796,23]
Function.prototype.arguments not supported [0:1004,12]
Function.prototype.arguments not supported [0:1006,47]
Function.prototype.arguments not supported [0:1008,19]
Function.prototype.arguments not supported [0:1009,27]
Copying declaration files
Writing package metadata

BUILD ERROR
Invalid regular expression: /*/: Nothing to repeat
Invalid regular expression: /*/: Nothing to repeat
SyntaxError: Invalid regular expression: /*/: Nothing to repeat
    at new RegExp (<anonymous>)
    at pkg.whitelistedNonPeerDependencies.map.value (node_modules/ng-packagr/lib/ng-v5/entry-point/write-package.transform.js:91:75)
    at Array.map (<anonymous>)
    at node_modules/ng-packagr/lib/ng-v5/entry-point/write-package.transform.js:91:62
    at Generator.next (<anonymous>)
    at node_modules/ng-packagr/lib/ng-v5/entry-point/write-package.transform.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (node_modules/ng-packagr/lib/ng-v5/entry-point/write-package.transform.js:3:12)
    at writePackageJson (node_modules/ng-packagr/lib/ng-v5/entry-point/write-package.transform.js:74:12)
    at Object.<anonymous> (node_modules/ng-packagr/lib/ng-v5/entry-point/write-package.transform.js:41:11)
    at Generator.next (<anonymous>)
    at fulfilled (node_modules/ng-packagr/lib/ng-v5/entry-point/write-package.transform.js:4:58)
error Command failed with exit code 1.
```

#### How To Reproduce

Checkout and install https://github.com/matheo/angular
then run `yarn build datasource` to see the error.

#### Expected Behaviour

A normal build with the bundles Ok.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            5.3.0
@angular/compiler:     8.0.1
rollup:                1.15.6
tsickle:               0.35.0
typescript:            3.4.5
rxjs: 6.5.2
node: 10.16.0
yarn: 1.16.0
```

Thanks!

**Comment by alan-agius4** [comment]
The regexp provided is not a valid regexp.

It should be `/.*/`

**Comment by matheo** [comment]
@alan-agius4 do you realize that the error comes from `pkg.whitelistedNonPeerDependencies.map.value (node_modules/ng-packagr/lib/ng-v5/entry-point/write-package.transform.js:91:75)`?
