### ISSUE TITLE
Cannot read property 'flatModuleFile' of undefined with sub modules

### ISSUE THREAD

**Issue by CSchulz** [ng-packagr/ng-packagr#1356]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

Followed the guide to package sub modules with a package.json:
```
{
  "ngPackage": {}
}
```

Leads to
```
[error] TypeError: Cannot read property 'flatModuleFile' of undefined
    at NgEntryPoint.$get (node_modules/ng-packagr/lib/ng-package-format/entry-point.js:89:26)
    at NgEntryPoint.get flatModuleFile [as flatModuleFile] (node_modules/ng-packagr/lib/ng-package-format/entry-point.js:107:21)
    at NgEntryPoint.get destinationFiles [as destinationFiles] (node_modules/ng-packagr/lib/ng-package-format/entry-point.js:72:37)
    at entryPoints.map.entryPoint (node_modules/ng-packagr/lib/ng-v5/package.transform.js:57:52)
    at Array.map (<anonymous>)
    at MapSubscriber.source$.pipe.operators_1.map.graph [as project] (node_modules/ng-packagr/lib/ng-v5/package.transform.js:56:77)
    at MapSubscriber._next (node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (node_modules/rxjs/internal/Subscriber.js:66:18)
    at SwitchMapSubscriber.notifyNext (node_modules/rxjs/internal/operators/switchMap.js:86:26)
    at InnerSubscriber._next (node_modules/rxjs/internal/InnerSubscriber.js:28:21)
```

#### How To Reproduce

Create a sub package and build the library.

#### Expected Behaviour

Should work 😄 

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            5.4.1
@angular/compiler:     8.1.3
rollup:                1.17.0
tsickle:               0.35.0
typescript:            3.4.5
```

#### workaround

```
{
  "ngPackage": {
    "lib": {
    }
  }
}
```

**Comment by alan-agius4** [comment]
Fixed in 5.4.2
