### ISSUE TITLE
Error when running ang8

### ISSUE THREAD

**Issue by mariohmol** [ng-packagr/ng-packagr#1365]
## Type of Issue

```
[ X ] Bug Report
[ ] Feature Request
```

## Description

_A bug: I have a plugin working with ang7
* https://github.com/jsGanttImproved/ng-gantt

but when I try to upgrade to 8, i receive an error
* https://github.com/jsGanttImproved/ng-gantt/tree/ang8

Here is the error on travis:
* https://travis-ci.com/jsGanttImproved/ng-gantt/builds/121763209

```
ng-packagr

/ng-gantt/node_modules/tslib/tslib.js:65
        extendStatics(d, b);
        ^

TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at Object.__extends (/ng-gantt/node_modules/tslib/tslib.js:65:9)
    at /ng-gantt/node_modules/@angular/compiler-cli/src/ngtsc/indexer/src/template.js:115:17
    at /ng-gantt/node_modules/@angular/compiler-cli/src/ngtsc/indexer/src/template.js:314:6
    at /ng-gantt/node_modules/@angular/compiler-cli/src/ngtsc/indexer/src/template.js:3:17
    at Object.<anonymous> (/ng-gantt/node_modules/@angular/compiler-cli/src/ngtsc/indexer/src/template.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at /ng-gantt/node_modules/@angular/compiler-cli/src/ngtsc/indexer/src/transform.js:20:22
    at /ng-gantt/node_modules/@angular/compiler-cli/src/ngtsc/indexer/src/transform.js:10:17
    at Object.<anonymous> (/ng-gantt/node_modules/@angular/compiler-cli/src/ngtsc/indexer/src/transform.js:16:3)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
```

#### How To Reproduce

_A bug: 
Clone this branch 
* https://github.com/jsGanttImproved/ng-gantt/tree/ang8

Try to run `ng-packagr -p ng-gantt/package.json`

#### Expected Behaviour

_A bug: Expected that this would build the same that happens in master branch, that is using angular 7 version.

Here the last build that was passing:

https://travis-ci.com/jsGanttImproved/ng-gantt/builds/121690974

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
```
I cant run this because the error occurs when run `ng-packagr`

This was the ang7 version:
```
node_modules/.bin/ng-packagr --version
ng-packagr:            4.4.5
@angular/compiler:     7.1.4
rollup:                0.67.4
tsickle:               0.27.2
typescript:            3.1.1
```

**Comment by alan-agius4** [comment]
The problem seems to be that you have multiple `@angular/compiler` defined as your dependencies, and also your `@angular/<package>` versions are not aligned.

Use this package.json
```json
{
  "name": "ng-gantt",
  "version": "0.0.0",
  "private": true,
  "license": "MIT",
  "scripts": {
    "start": "ng serve",
    "build": "npm run copy && ng build",
    "copy": "cp -R dist/ng-gantt src/ng-gantt",
    "build:app": "npm run copy && ng build --project packages && rimraf src/ng-gantt",
    "build:lib": "rimraf dist && ng-packagr -p ng-gantt/package.json",
    "publish-npm": "npm run build:lib && cd dist/ng-gantt && npm publish",
    "reload": "npm run build:lib && npm run build && npm run start",
    "dev": "cd dist/app && http-server",
    "test": "ng test dev --watch=false && npm run e2e",
    "unittest": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "kill": "kill -9 $(lsof -t -i:4200)",
    "reinstall": "rm package-lock.json && rm -rf node_modules && npm i",
    "sass:rebuild": "npm rebuild node-sass"
  },
  "dependencies": {
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/http": "^7.2.15",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "core-js": "^2.4.1",
    "rxjs": "^6.4.0",
    "webpack": "^4.16.1",
    "zone.js": "^0.9.0",
    "jsgantt-improved": "^2.4.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.802.0",
    "@angular/cli": "~8.2.0",
    "@angular/compiler-cli": "~8.2.0",
    "@angular/language-service": "~8.2.0",
    "@types/jasmine": "3.3.8",
    "@types/node": "~10.1.0",
    "codelyzer": "~5.0.0",
    "cpr": "^3.0.0",
    "jasmine": "^3.3.0",
    "jasmine-core": "^3.3.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^2.0.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "rimraf": "^2.6.1",
    "ts-node": "^8.0.0",
    "tslib": "^1.9.0",
    "tslint": "~5.15.0",
    "ng-packagr": "4.4.5",
    "rollup": "0.67.4",
    "tsickle": "^0.36.0",
    "typescript": "~3.5.0"
  }
}
```

Also it is important to highlight that in ng-packagr version 4.x, Angular version 8 is not supported. Angular version 8 is supported by ng-packagr 5+

**Comment by mariohmol** [comment]
Hi .. thanks for answering.. but still not working.. now having this error:


```
 Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config 
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist



BUILD ERROR
TypeError: Cannot read property 'directoryExists' of undefined
    at Object.directoryProbablyExists (/ng-gantt/node_modules/typescript/lib/typescript.js:12397:22)
    at tryLoadModuleUsingBaseUrl (/ng-gantt/node_modules/typescript/lib/typescript.js:27027:50)
    at tryLoadModuleUsingOptionalResolutionSettings (/ng-gantt/node_modules/typescript/lib/typescript.js:26931:20)
    at tryResolve (/ng-gantt/node_modules/typescript/lib/typescript.js:27072:28)
    at /ng-gantt/node_modules/typescript/lib/typescript.js:27064:69
    at Object.forEach (/ng-gantt/node_modules/typescript/lib/typescript.js:280:30)
    at nodeModuleNameResolverWorker (/ng-gantt/node_modules/typescript/lib/typescript.js:27064:25)
    at nodeModuleNameResolver (/ng-gantt/node_modules/typescript/lib/typescript.js:27057:16)
    at Object.resolveModuleName (/ng-gantt/node_modules/typescript/lib/typescript.js:26834:30)
    at Object.resolveModuleName (/ng-gantt/node_modules/tsickle/src/googmodule.js:132:29)

Error: TypeError: Cannot read property 'directoryExists' of undefined
    at Object.directoryProbablyExists (/ng-gantt/node_modules/typescript/lib/typescript.js:12397:22)
    at tryLoadModuleUsingBaseUrl (/ng-gantt/node_modules/typescript/lib/typescript.js:27027:50)
    at tryLoadModuleUsingOptionalResolutionSettings (/ng-gantt/node_modules/typescript/lib/typescript.js:26931:20)
    at tryResolve (/ng-gantt/node_modules/typescript/lib/typescript.js:27072:28)
    at /Users/mariohmol/projetos/ng-gantt/node_modules/typescript/lib/typescript.js:27064:69
    at Object.forEach (/Users/mariohmol/projetos/ng-gantt/node_modules/typescript/lib/typescript.js:280:30)
    at nodeModuleNameResolverWorker (/Users/mariohmol/projetos/ng-gantt/node_modules/typescript/lib/typescript.js:27064:25)
    at nodeModuleNameResolver (/Users/mariohmol/projetos/ng-gantt/node_modules/typescript/lib/typescript.js:27057:16)
    at Object.resolveModuleName (/ng-gantt/node_modules/typescript/lib/typescript.js:26834:30)
    at Object.resolveModuleName (/ng-gantt/node_modules/tsickle/src/googmodule.js:132:29)

    at Object.<anonymous> (/ng-gantt/node_modules/ng-packagr/lib/ngc/compile-source-files.js:40:68)
    at Generator.next (<anonymous>)
    at /ng-gantt/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/ng-gantt/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/ng-gantt/node_modules/ng-packagr/lib/ngc/compile-source-files.js:17:12)
    at Object.<anonymous> (/ng-gantt/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:31:32)
    at Generator.next (<anonymous>)
    at /ng-gantt/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
```

**Comment by mariohmol** [comment]
Here is the build https://travis-ci.com/jsGanttImproved/ng-gantt/builds/121972040

**Comment by mariohmol** [comment]
Maybe is related https://github.com/angular/angular/pull/26738

**Comment by alan-agius4** [comment]
Can you update to the latest version of ngpackagr and tsickle.

**Comment by mariohmol** [comment]
worked!! thank you

**Comment by brq-cr** [comment]
dependencies/`@angular/cli` and devDependencies/`@angular/compiler-cli` must have the same version number.

**Comment by hvallenilla** [comment]
> dependencies/`@angular/cli` and devDependencies/`@angular/compiler-cli` both must have the same version number.

Thanks, this fix my issue !!!
