### ISSUE TITLE
ERROR: Unknown version 76 of android

### ISSUE THREAD

**Issue by seamusjunior** [ng-packagr/ng-packagr#1592]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

ERROR: Unknown version 76 of android

#### How To Reproduce

PS C:\AngularTemplate\Allsop.Angular.Common> npm run packagr

> allsop-angular-common@1.1.7 packagr C:\AngularTemplate\Allsop.Angular.Common
> ng-packagr -p ng-package.json

Building Angular Package

------------------------------------------------------------------------------
Building entry point 'allsop-angular-common'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
ERROR: Unknown version 76 of android
npm ERR! code ELIFECYCLE
npm ERR! errno 111
npm ERR! allsop-angular-common@1.1.7 packagr: `ng-packagr -p ng-package.json`
npm ERR! Exit status 111
npm ERR!
npm ERR! Failed at the allsop-angular-common@1.1.7 packagr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kevin\AppData\Roaming\npm-cache\_logs\2020-04-01T15_43_18_025Z-debug.log

#### Expected Behaviour

Build Package

#### Version Information

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\kevin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'packagr'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.1
4 verbose run-script [ 'prepackagr', 'packagr', 'postpackagr' ]
5 info lifecycle allsop-angular-common@1.1.7~prepackagr: allsop-angular-common@1.1.7
6 info lifecycle allsop-angular-common@1.1.7~packagr: allsop-angular-common@1.1.7
7 verbose lifecycle allsop-angular-common@1.1.7~packagr: unsafe-perm in lifecycle true
8 verbose lifecycle allsop-angular-common@1.1.7~packagr: PATH: C:\Users\kevin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\AngularTemplate\Allsop.Angular.Common\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\kevin\AppData\Local\Microsoft\WindowsApps;;C:\Users\kevin\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\kevin\AppData\Local\Programs\Fiddler;C:\Users\kevin\AppData\Roaming\npm;C:\Users\kevin\.dotnet\tools
9 verbose lifecycle allsop-angular-common@1.1.7~packagr: CWD: C:\AngularTemplate\Allsop.Angular.Common
10 silly lifecycle allsop-angular-common@1.1.7~packagr: Args: [ '/d /s /c', 'ng-packagr -p ng-package.json' ]
11 silly lifecycle allsop-angular-common@1.1.7~packagr: Returned: code: 111  signal: null
12 info lifecycle allsop-angular-common@1.1.7~packagr: Failed to exec packagr script
13 verbose stack Error: allsop-angular-common@1.1.7 packagr: `ng-packagr -p ng-package.json`
13 verbose stack Exit status 111
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\kevin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\kevin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid allsop-angular-common@1.1.7
15 verbose cwd C:\AngularTemplate\Allsop.Angular.Common
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kevin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "packagr"
18 verbose node v12.16.1
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 111
22 error allsop-angular-common@1.1.7 packagr: `ng-packagr -p ng-package.json`
22 error Exit status 111
23 error Failed at the allsop-angular-common@1.1.7 packagr script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 111, true ]

```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
Which version of my-packagr are you using?

**Comment by seamusjunior** [comment]
I originally using - 5.7.1 then upgrade a few times now on 9.0.0.  No change.

**Comment by seamusjunior** [comment]
What does the error even mean?  What has Android got to do with it?

**Comment by alan-agius4** [comment]
Should be solved. Please update to 9.1.3.
