### ISSUE TITLE
ng-packager fails to bundle library with components

### ISSUE THREAD

**Issue by Eddman** [ng-packagr/ng-packagr#1609]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
After upgrading to `ng-packagr@9.1.0` that bundles new `rollup` I'm not able to build my library anymore. I'm hitting the following error:
```
Compiling TypeScript sources through ngc
Bundling to FESM2015
Error: 'import' and 'export' may only appear at the top level
    at error (.../node_modules/ng-packagr/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (.../node_modules/ng-packagr/node_modules/rollup/dist/shared/node-entry.js:9825:16)
    at tryParse (.../node_modules/ng-packagr/node_modules/rollup/dist/shared/node-entry.js:9718:23)
    at Module.setSource (.../node_modules/ng-packagr/node_modules/rollup/dist/shared/node-entry.js:10081:33)
    at .../node_modules/ng-packagr/node_modules/rollup/dist/shared/node-entry.js:12367:20
    at runNextTicks (internal/process/task_queues.js:59:5)
    at processImmediate (internal/timers.js:412:9)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async Promise.all (index 0) {
  code: 'PARSE_ERROR',
  parserError: SyntaxError: 'import' and 'export' may only appear at the top level (4:0)
      at Object.pp$4.raise (.../node_modules/ng-packagr/node_modules/acorn/dist/acorn.js:2840:15)
      at Object.pp$1.parseStatement (.../node_modules/ng-packagr/node_modules/acorn/dist/acorn.js:859:18)
      at Object.parseStatement (.../node_modules/ng-packagr/node_modules/rollup/dist/shared/node-entry.js:11830:30)
      at Object.pp$1.parseBlock (.../node_modules/ng-packagr/node_modules/acorn/dist/acorn.js:1161:23)
      at Object.pp$3.parseFunctionBody (.../node_modules/ng-packagr/node_modules/acorn/dist/acorn.js:2686:24)
      at Object.pp$1.parseFunction (.../node_modules/ng-packagr/node_modules/acorn/dist/acorn.js:1283:10)
      at Object.pp$3.parseExprAtom (.../node_modules/ng-packagr/node_modules/acorn/dist/acorn.js:2244:19)
      at Object.parseExprAtom (.../node_modules/ng-packagr/node_modules/rollup/dist/shared/node-entry.js:11812:30)
      at Object.pp$3.parseExprSubscripts (.../node_modules/ng-packagr/node_modules/acorn/dist/acorn.js:2092:21)
      at Object.pp$3.parseMaybeUnary (.../node_modules/ng-packagr/node_modules/acorn/dist/acorn.js:2069:19) {
    pos: 135,
    loc: Position { line: 4, column: 0 },
    raisedAt: 141
  },
  pos: 135,
  loc: {
    column: 0,
    file: '.../dist/dbg-riskit/angular-view/esm2015/lib/flex.component.js',
    line: 1
  },
  frame: '1: import { __decorate, __metadata } from "tslib";\n' +
    '   ^\n' +
    "2: import { ChangeDetectionStrategy, Component, Input } from '@angular/core';\n" +
    '3: let FlexComponent = class FlexComponent {'
}
ERROR: 'import' and 'export' may only appear at the top level
An unhandled exception occurred: 'import' and 'export' may only appear at the top level
```
The file that throws error:
```js
import { __decorate, __metadata } from "tslib";
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
let FlexComponent = class FlexComponent {
    constructor() {
        this.wrapContent = false;
    }
};
__decorate([
    Input(),
    __metadata("design:type", Boolean)
], FlexComponent.prototype, "wrapContent", void 0);
FlexComponent = __decorate([
    Component({
        moduleId: module.id,
        selector: 'risk-flex',
        template: '<ng-content></ng-content>',
        host: {
            '[class.risk-flex]': '!wrapContent',
            '[class.risk-flex-wrap]': 'wrapContent'
        },
        changeDetection: ChangeDetectionStrategy.OnPush,
        preserveWhitespaces: false,
        styles: [":host{display:block;padding:0;margin:0}:host>*{vertical-align:bottom}", ":host{display:-webkit-flex;display:-ms-flexbox;display:flex}"]
    })
], FlexComponent);
export { FlexComponent };
```

Previously running `ng-packagr@9.0.3` I had no problem.

#### How To Reproduce
There is no obvious way to reproduce, at least I wasn't able to reproduce on other modules. But I can say it is the first module that does contain components. Other modules do contain only services.

#### Expected Behaviour

Rollup will not fail to bundle my library.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            9.1.1
@angular/compiler:     9.1.3
rollup:                2.6.1
tsickle:               0.38.1
typescript:            3.8.3
node: 12.16.2
npm: 6.14.4
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by rajdnexgen** [comment]
I am also getting the same error while bundling the library. Got same issue discussion in following url : https://github.com/rollup/plugins/issues/304

**Comment by Eddman** [comment]
So after downgrading commonjs plugin my project is building again. Just had to add the following line into `package.json`:
```json
        "@rollup/plugin-commonjs": "11.0.2",
```
I think it is not really needed to keep this one open as this is clearly a bug in rollup/plugins repo.

**Comment by alan-agius4** [comment]
Should be solved since https://github.com/rollup/plugins/issues/304 has been closed.
