### ISSUE TITLE
Version 9 throws No valid export main found for rollup-plugin-sourcemaps

### ISSUE THREAD

**Issue by cmarois** [ng-packagr/ng-packagr#1628]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
When trying to execute ng-packager > 9, the command fails with 'No valid exports main found for '.../node_modules/ng-packagr/node_modules/rollup-plugin-sourcemaps'

_A bug: please describe the error that you encountered_
[error] Error: No valid exports main found for '.../node_modules/ng-packagr/node_modules/rollup-plugin-sourcemaps'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/christianmarois/dev/lytica/SupplyLens/src/testlib/node_modules/ng-packagr/lib/flatten/rollup.js:14:20)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)

#### How To Reproduce

`node_modules/.bin/ng-packagr --version`

Throws an unhandled error as mentionned above.

#### Expected Behaviour

Should run.

#### Version Information

```
ng-packagr: 9.x
@angular/*: 9.1.4
typescript: 3.8.3
rxjs: 6.5.5
node: 13.6
yarn: 1.21.1
```

**Comment by alan-agius4** [comment]
Should be solved as per https://github.com/maxdavidson/rollup-plugin-sourcemaps/issues/117
