### ISSUE TITLE
Dependencies for 9.1.5 - Cannot find module '@angular/compiler-cli/ngcc'

### ISSUE THREAD

**Issue by AndersBKnudsen** [ng-packagr/ng-packagr#1668]
Which dependencies does the version 9.1.5 have? 

I installed it, but got an error 
Error: Cannot find module '@angular/compiler-cli/ngcc'

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '@angular/compiler-cli/ngcc'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

**Comment by JoostK** [comment]
You'll need to use Angular 9
