### ISSUE TITLE
ERROR: Could not resolve module @angular/core

### ISSUE THREAD

**Issue by AndreaDiCioccio** [ng-packagr/ng-packagr#1795]
## Type of Issue

```
[* ] Bug Report
[ ] Feature Request
```

## Description
I'm trying to make a library, without ng-packagr works fine but I need to include assets.
on build i get error "ERROR: Could not resolve module @angular/core"
/core is in node_modules/@angular

```
npm run build:lib

> rating-stars-library@0.0.6 build:lib /home/andrea/lavoro/angular/librerie/RatingStarsLibrary
> ng-packagr -p projects/ngx-rating-stars/package.json

Building Angular Package

------------------------------------------------------------------------------
Building entry point 'ngx-rating-stars'
------------------------------------------------------------------------------
Compiling TypeScript sources through NGC
ERROR: Could not resolve module @angular/core
npm ERR! code ELIFECYCLE
npm ERR! errno 111
npm ERR! rating-stars-library@0.0.6 build:lib: `ng-packagr -p projects/ngx-rating-stars/package.json`
npm ERR! Exit status 111
npm ERR! 
npm ERR! Failed at the rating-stars-library@0.0.6 build:lib script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/andrea/.npm/_logs/2020-11-20T10_34_40_919Z-debug.log
```
log
```
cat /home/andrea/.npm/_logs/2020-11-20T10_34_40_919Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'run', 'build:lib' ]
2 info using npm@6.14.5
3 info using node@v10.20.1
4 verbose run-script [ 'prebuild:lib', 'build:lib', 'postbuild:lib' ]
5 info lifecycle rating-stars-library@0.0.6~prebuild:lib: rating-stars-library@0.0.6
6 info lifecycle rating-stars-library@0.0.6~build:lib: rating-stars-library@0.0.6
7 verbose lifecycle rating-stars-library@0.0.6~build:lib: unsafe-perm in lifecycle true
8 verbose lifecycle rating-stars-library@0.0.6~build:lib: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/andrea/lavoro/angular/librerie/RatingStarsLibrary/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle rating-stars-library@0.0.6~build:lib: CWD: /home/andrea/lavoro/angular/librerie/RatingStarsLibrary
10 silly lifecycle rating-stars-library@0.0.6~build:lib: Args: [ '-c', 'ng-packagr -p projects/ngx-rating-stars/package.json' ]
11 silly lifecycle rating-stars-library@0.0.6~build:lib: Returned: code: 111  signal: null
12 info lifecycle rating-stars-library@0.0.6~build:lib: Failed to exec build:lib script
13 verbose stack Error: rating-stars-library@0.0.6 build:lib: `ng-packagr -p projects/ngx-rating-stars/package.json`
13 verbose stack Exit status 111
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid rating-stars-library@0.0.6
15 verbose cwd /home/andrea/lavoro/angular/librerie/RatingStarsLibrary
16 verbose Linux 5.4.0-3-amd64
17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "build:lib"
18 verbose node v10.20.1
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 111
22 error rating-stars-library@0.0.6 build:lib: `ng-packagr -p projects/ngx-rating-stars/package.json`
22 error Exit status 111
23 error Failed at the rating-stars-library@0.0.6 build:lib script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 111, true ]

```

#### How To Reproduce
root package.json:
```
 {
  "name": "rating-stars-library",
  "version": "0.0.6",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build-bkp": "ng build",
    "build:lib": "ng-packagr -p projects/ngx-rating-stars/package.json",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": false,
  "dependencies": {
    "@angular/animations": "~10.0.6",
    "@angular/common": "~10.0.6",
    "@angular/compiler": "~10.0.6",
    "@angular/core": "^10.0.14",
    "@angular/forms": "~10.0.6",
    "@angular/platform-browser": "~10.0.6",
    "@angular/platform-browser-dynamic": "~10.0.6",
    "@angular/router": "~10.0.6",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.5",
    "@angular-devkit/build-ng-packagr": "~0.1000.8",
    "@angular/cli": "~10.0.5",
    "@angular/compiler-cli": "~10.0.6",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "ng-packagr": "^10.0.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  }
}
```
library package.json
```
{
    "$schema": "../../node_modules/ng-packagr/package.schema.json",
    "name": "ngx-rating-stars",
    "version": "0.0.6",
    "description": "A simple rating stars component",
    "author": "Andrea Di Cioccio",
    "keywords": ["angular", "rating", "stars"],
    "peerDependencies": {
        "@angular/common": "^10.0.14",
        "@angular/core": "^10.0.14"
    },
    "dependencies": {
        "tslib": "^2.0.0"
    },
    "ngPackage": {
        "lib": {
          "entryFile": "/src/public-api.ts"
        },
        "dest": "/dist/ngx-rating-stars"
      }
}
```

#### Expected Behaviour

I want avoid the error and build right

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 11.0.0-next.3
@angular/compiler: 10.0.14
rollup: 2.10.9          
typescript: 3.9.7
npm: 6.14.5
```

**Comment by alan-agius4** [comment]
Hi @AndreaDiCioccio, without a reproduction it's hard to tell what is happening. Although ng-packagr version 11 is compatible only with Angular 11.x

**Comment by AndreaDiCioccio** [comment]
OK, thanks for reply. I installed ng-packagr 10.1.2 and get the same error (ERROR: Could not resolve module @angular/core). [This](https://github.com/AndreaDiCioccio/angular-library-message) is the project, I dont know how to reproduce it, but i have not done anything so complicated as you can see.
I followed [this](https://medium.com/@nikolasleblanc/building-an-angular-4-component-library-with-the-angular-cli-and-ng-packagr-53b2ade0701e) tutorial, it is for angular 4 but I found it in README.md of ng-packagr on this github.
What do u think about?

**Comment by alan-agius4** [comment]
It looks like the issue is caused by https://github.com/AndreaDiCioccio/angular-library-message/blob/a29eb4e20ea8aa64d0ab539b5326b942873e0490/projects/ngx-message/package.json#L12-L17

The config there is not correct as all the paths starts with `/` (root path) which of course none of those file exists. Also this config is redundant because in an Angular library that is generated by the CLI ng-packagr configuration is located here: https://github.com/AndreaDiCioccio/angular-library-message/blob/master/projects/ngx-message/ng-package.json

**Comment by alan-agius4** [comment]
For a more up to date article on libraries please see: https://angular.io/guide/creating-libraries
