### ISSUE TITLE
Question: How can we use a compiled ng-packagr library for Angular Elements? (Not a bug)

### ISSUE THREAD

**Issue by tyh77** [ng-packagr/ng-packagr#1812]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] Seeking guidance
```

## Description

I'm getting an error from `platformBrowserDynamic().bootstrapModule(<moduleName>)` while trying to initialize my NgModule for an Angular Elements, which is a standalone parent Angular app to an Angular library that I compiled using **ng-packagr** and linked via `npm link`:
```
zone.js:690 Unhandled Promise rejection: Can't resolve all parameters for ApplicationModule: (?). 
    at syntaxError (compiler.js:2531)
    at CompileMetadataResolver.rT7n.CompileMetadataResolver._getDependenciesMetadata (compiler.js:22417)
    at CompileMetadataResolver.rT7n.CompileMetadataResolver._getTypeMetadata (compiler.js:22309)
    at CompileMetadataResolver.rT7n.CompileMetadataResolver.getNgModuleMetadata (compiler.js:22177)
    at CompileMetadataResolver.rT7n.CompileMetadataResolver.getNgModuleSummary (compiler.js:21984)
    at compiler.js:22098
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.rT7n.CompileMetadataResolver.getNgModuleMetadata (compiler.js:22086)
    at CompileMetadataResolver.rT7n.CompileMetadataResolver.getNgModuleSummary (compiler.js:21984)
    at compiler.js:22071 Error: Can't resolve all parameters for ApplicationModule: (?).
    at syntaxError (https://localhost:4321/dist/ngx-test-console-web-part.js:159604:17)
    at CompileMetadataResolver.rT7n.CompileMetadataResolver._getDependenciesMetadata (https://localhost:4321/dist/ngx-test-console-web-part.js:179490:35)
    at CompileMetadataResolver.rT7n.CompileMetadataResolver._getTypeMetadata (https://localhost:4321/dist/ngx-test-console-web-part.js:179382:26)
    at CompileMetadataResolver.rT7n.CompileMetadataResolver.getNgModuleMetadata (https://localhost:4321/dist/ngx-test-console-web-part.js:179250:24)
    at CompileMetadataResolver.rT7n.CompileMetadataResolver.getNgModuleSummary (https://localhost:4321/dist/ngx-test-console-web-part.js:179057:35)
    at https://localhost:4321/dist/ngx-test-console-web-part.js:179171:51
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.rT7n.CompileMetadataResolver.getNgModuleMetadata (https://localhost:4321/dist/ngx-test-console-web-part.js:179159:49)
    at CompileMetadataResolver.rT7n.CompileMetadataResolver.getNgModuleSummary (https://localhost:4321/dist/ngx-test-console-web-part.js:179057:35)
    at https://localhost:4321/dist/ngx-test-console-web-part.js:179144:55
```

After some reading, it seems like PlatformBrowserDynamic uses JIT compilation for the module, whereas the compiled library is AOT-compatible. I couldn't seem to find exact documentation that states whether the compiled dist library is AOT or JIT, but this is my best guess for the error that I'm facing. 

I suspect that the JIT compiler is being used on a non-JIT NgModule imported from an Angular Library.

#### Version Information
```
ng-packagr: 9.0.0
@angular/*: 9.0.7
typescript: 3.7.5
rxjs: 6.5.4
node: 10.22.1
npm/yarn: 6.14.6
```

#### Additional Info
If my suspicions are correct and that I would need to bootstrap this module differently, I would have to use AOT compilation to bootstrap this ngModule, but there doesn't seem to be an ngfactory in the dist output?

JIT compilation is also seemingly impossible for the ng-packagr.

Any advice?

**Comment by flash-me** [comment]
> while trying to initialize my NgModule for an Angular Elements, which is a standalone parent Angular app to an Angular library that I compiled using ng-packagr and linked via npm link:

I'm not really understanding this, but here are some Information to some mentioned keywords: 
`platformBrowserDynamic` depends on the @angular/compiler, which is dropped during AOT compilation.

> I suspect that the JIT compiler is being used on a non-JIT NgModule imported from an Angular Library.
Donno what "non-JIT" indicates, but by default, libraries are not AOT compiled. However they can be compiled with Ivy. 

> Can't resolve all parameters for ApplicationModule: (?).
As the already error describes pretty clearly, a dependency used by ApplicationModule could not be resolved. 

> JIT compilation is also seemingly impossible for the ng-packagr.
JIT stands for just-in-time. If you don't AOT compile your angular application, it will be compiled during runtime in the browser. So no, ng-packagr is neither a JavaScript runtime nor a DOM renderer and can't JIT compile.

cheers
flash ⚡

**Comment by alan-agius4** [comment]
Closing as this is currently out of scope.
