### ISSUE TITLE
Angular build fails

### ISSUE THREAD

**Issue by zehavibarak** [ng-packagr/ng-packagr#2038]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

```bash
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dist'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle bizdoc.core@1.4.3~predist: bizdoc.core@1.4.3
6 info lifecycle bizdoc.core@1.4.3~dist: bizdoc.core@1.4.3
7 verbose lifecycle bizdoc.core@1.4.3~dist: unsafe-perm in lifecycle true
8 verbose lifecycle bizdoc.core@1.4.3~dist: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;...
9 verbose lifecycle bizdoc.core@1.4.3~dist: CWD: C:\...\Angular\ClientApp
10 silly lifecycle bizdoc.core@1.4.3~dist: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'npm run packagr && npm run copy-themes && npm run copy-assets && npm run publish'
10 silly lifecycle ]
11 silly lifecycle bizdoc.core@1.4.3~dist: Returned: code: 1  signal: null
12 info lifecycle bizdoc.core@1.4.3~dist: Failed to exec dist script
13 verbose stack Error: bizdoc.core@1.4.3 dist: `npm run packagr && npm run copy-themes && npm run copy-assets && npm run publish`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:376:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:376:20)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid bizdoc.core@1.4.3
15 verbose cwd C:\Users\barak\source\repos\BizDoc.Core\Angular\ClientApp
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
18 verbose node v14.17.0
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error bizdoc.core@1.4.3 dist: `npm run packagr && npm run copy-themes && npm run copy-assets && npm run publish`
22 error Exit status 1
23 error Failed at the bizdoc.core@1.4.3 dist script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

#### HowTo Reproduce

> npm run packagr

Output "Compiling with Angular in legacy View Engine compilation mode."

Produces _Maximum call stack size exceeded._

#### Version Information

```
ng-packagr:            12.2.0-next.0
@angular/compiler:     12.1.4
rollup:                2.55.1
typescript:            4.3.5
```

**Comment by zehavibarak** [comment]
package.json:

```json
{
  "dependencies": {
    "@angular/animations": "^12.1.4",
    "@angular/cdk": "^12.1.4",
    "@angular/common": "^12.1.4",
    "@angular/compiler": "^12.1.4",
    "@angular/core": "^12.1.4",
    "@angular/flex-layout": "^12.0.0-beta.34",
    "@angular/forms": "^12.1.4",
    "@angular/material": "^12.1.4",
    "@angular/material-moment-adapter": "^12.1.4",
    "@angular/platform-browser": "^12.1.4",
    "@angular/platform-browser-dynamic": "^12.1.4",
    "@angular/platform-server": "^12.1.4",
    "@angular/router": "^12.1.4",
    "@ctrl/ngx-emoji-mart": "^6.0.0",
    "@microsoft/signalr": "^5.0.8",
    "@syncfusion/ej2": "^19.2.49",
    "@syncfusion/ej2-angular-charts": "^19.2.49",
    "@syncfusion/ej2-angular-circulargauge": "^19.2.49",
    "@syncfusion/ej2-angular-diagrams": "^19.2.49",
    "@syncfusion/ej2-angular-grids": "^19.2.49",
    "@syncfusion/ej2-angular-kanban": "^19.2.47",
    "@syncfusion/ej2-angular-layouts": "^19.2.48",
    "@syncfusion/ej2-angular-pivotview": "^19.2.49",
    "@syncfusion/ej2-angular-schedule": "^19.2.49",
    "@syncfusion/ej2-angular-spreadsheet": "^19.2.49",
    "@syncfusion/ej2-base": "^19.2.49",
    "@teamhive/lottie-player": "^1.0.0",
    "ajv": "^8.6.2",
    "brace": "^0.11.1",
    "cookie": "^0.4.1",
    "firebase": "^8.8.1",
    "hammerjs": "~2",
    "lottie-web": "^5.7.12",
    "moment": "^2.29.1",
    "ngx-cookie-service": "^12.0.2",
    "ngx-moment": "^5.0.0",
    "rxjs": "^7.3.0",
    "xlsx": "^0.17.0",
    "zone.js": "^0.11.4"
  },
  "devDependencies": {
    "google-closure-compiler": "^20210601.0.0",
    "@angular-devkit/build-angular": "^12.1.4",
    "@angular-devkit/build-webpack": "^0.1201.4",
    "@angular/cli": "^12.1.4",
    "@angular/compiler-cli": "^12.1.4",
    "@types/googlemaps": "^3.43.3",
    "@types/jasmine": "^3.8.2",
    "@types/jasminewd2": "^2.0.10",
    "@types/node": "^16.4.10",
    "caniuse-lite": "^1.0.30001248",
    "jasmine-core": "^3.8.0",
    "jasmine-spec-reporter": "^7.0.0",
    "karma": "^6.3.4",
    "karma-chrome-launcher": "^3.1",
    "karma-cli": "^2.0",
    "karma-coverage-istanbul-reporter": "^3.0.3",
    "karma-jasmine": "^4.0.1",
    "karma-jasmine-html-reporter": "^1.7.0",
    "ng-packagr": "^12.1.2",
    "protractor": "^7.0.0",
    "reflect-metadata": "^0.1",
    "rxjs-tslint": "^0.1.8",
    "ts-node": "^10.1.0",
    "tslib": "^2.3.0",
    "tslint": "^6.1.3",
    "typescript": "4.3",
    "webpack-cli": "^4.7.2"
  },
}
```

**Comment by alan-agius4** [comment]
@zehavibarak, please share a runnable minimal reproduction.

 A good way to make a minimal repro is to create a new app via `ng new repro —-no-create-application` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by zehavibarak** [comment]
https://github.com/zehavibarak/ng-packagr-repro/

**Comment by alan-agius4** [comment]
It appears that the public-api files doesn’t reference any files https://github.com/zehavibarak/ng-packagr-repro

Also, it appears that you are trying to build an application with ng-packagr, which is not a supported usecase.

To generate a library in the Angular CLI use `ng generate library my-lib`

**Comment by zehavibarak** [comment]
Generate a library? I wish to package my library

**Comment by alan-agius4** [comment]
In the reproduction shared you have an application not a library.

**Comment by zehavibarak** [comment]
It is *minimum* repro of a library, which procuces an error.

**Comment by alan-agius4** [comment]
I am unable to reproduce with the reproduction provided

```
➜  ng-packagr-repro git:(main) ✗ yarn packagr
yarn run v1.22.10
$ ng-packagr -p ng-package.json
Building Angular Package

------------------------------------------------------------------------------
Building entry point 'repro'
------------------------------------------------------------------------------
✖ Compiling with Angular in legacy View Engine compilation mode.
repro.ts:5:15 - error TS2306: File '//ng-packagr-repro/public-api.ts' is not a module.

5 export * from './public-api';
                ~~~~~~~~~~~~~~

error Command failed with exit code 1.
```

**Comment by zehavibarak** [comment]
Waw, you were extremely fast in closing this one!

**Comment by alan-agius4** [comment]
Feel free to open a new issue when you have a minimal reproduction that we can try.  Until then, there is nothing actionable here.

**Comment by zehavibarak** [comment]
Can you confirm you're capacity in this forum?

**Comment by zehavibarak** [comment]
I'm sorry, can you confirm you're capacity in this forum so I can share more code?

**Comment by SchnWalter** [comment]
If you follow the guidelines, you should be able to build a library. Also, that's not a minimal reproduction, it has a ton a file and it's actually an application, not a library. You should go to angular.io and read the relevant documentation.

**Comment by zehavibarak** [comment]
It is a library, a large one. I test it as an application. I have published it before, and for some reason cannot publish it now.

**Comment by zehavibarak** [comment]
I've reagraned my code as @SchnWalter suggested and used `npm publish` rather than calling ng-packagr directly and now it works!
