### ISSUE TITLE
Fatal error: too many writes on closed pipe

### ISSUE THREAD

**Issue by mgameover** [ng-packagr/ng-packagr#2085]
## Fatal error: too many writes on closed pipe

```
[x] Bug Report
[ ] Feature Request
```

## Description

After updating ng-packagr from v12.2.1 to v12.2.2, build process takes much more time and the following error appears at the end.

```
fatal error: too many writes on closed pipe

goroutine 6 [running]:
runtime.throw({0x829e2, 0x1e})
        /usr/local/go/src/runtime/panic.go:1198 +0x7 fp=0x452ec8 sp=0x452ea0 pc=0x12000007
os.sigpipe()
        /usr/local/go/src/runtime/os_js.go:143 +0x2 fp=0x452ee0 sp=0x452ec8 pc=0x137c0002
os.epipecheck(...)
        /usr/local/go/src/os/file_unix.go:196
os.(*File).Write(0x40c020, {0x62ba80, 0x21, 0x40})
        /usr/local/go/src/os/file.go:184 +0x25 fp=0x452f68 sp=0x452ee0 pc=0x15b70025
main.runService.func1(0x44c190, 0x422d10)
main.runService.func1(0x44c190, 0x422d10)
        /Users/evan/dev/esbuild/cmd/esbuild/service.go:70 +0x5 fp=0x452fd0 sp=0x452f68 pc=0x1d560005
runtime.goexit()
        /usr/local/go/src/runtime/asm_wasm.s:431 +0x1 fp=0x452fd8 sp=0x452fd0 pc=0x13d10001
created by main.runService
        /Users/evan/dev/esbuild/cmd/esbuild/service.go:64 +0xe

goroutine fatal error: too many writes on closed pipe1fatal error:

goroutine 6 [runningtoo many writes on closed pipe []:

chan receiveruntime.throw
goroutine (]:
6{syscall.fsCall(0x829e2 [{, running0x7612d0x1e]:
, }runtime.throw0x4)
(}      {, /usr/local/go/src/runtime/panic.go0x829e2{:, 0x47bb5011980x1e,  +}0x50x7, 0x5})
        /usr/local/go/src/syscall/fs_js.go:521 +0x13
syscall.Read(0x0, {0x4ec000, 0x4000, 0x4000})
        /usr/local/go/src/syscall/fs_js.go:389 +0xc
internal/poll.ignoringEINTRIO(...)
        /usr/local/go/src/internal/poll/fd_unix.go: fp=582)

internal/poll.(*FD).Read(0x44a060, {0x4ec000, 0x4000, 0x4000}/usr/local/go/src/runtime/panic.go)
0x452ec8 sp=0x452ea0 pc=0x12000007
os.sigpipe:     (1198 +0x7 fp=0x452ec8 sp=0x452ea0 pc=0x12000007
)
        /usr/local/go/src/runtime/os_js.go:143 +0x2 fp=0x452ee0 sp=0x452ec8 pc=0x137c0002
os.epipecheck/usr/local/go/src/internal/poll/fd_unix.goos.sigpipe:(
```

#### How To Reproduce

Run the following command:
 `node --max-old-space-size=8192 ./node_modules/@angular/cli/bin/ng build library-name`

#### Version Information

$ node_modules/.bin/ng-packagr --version

```
ng-packagr:            12.2.2
@angular/compiler:     12.2.7
rollup:                2.57.0
typescript:            4.3.5
```

**Comment by mgameover** [comment]
Hmm, the thing is that ng-packagr v12.2.1 works fine. That might be a dependency issue. What do you think?
