### ISSUE TITLE
Migrating to Angular 13 : Cannot find global type 'BigInt'

### ISSUE THREAD

**Issue by JeanMeche** [ng-packagr/ng-packagr#2282]
## Type of Issue

```
[*] Bug Report
```

## Description

[error] Error: [91merror[0m[90m TS2318: [0mCannot find global type 'BigInt'.

```
    at compileSourceFiles (/home/rieglerm/dev/ngx-ui/node_modules/ng-packagr/lib/ngc/compile-source-files.js:145:15)
    at async /home/rieglerm/dev/ngx-ui/node_modules/ng-packagr/lib/ng-package/entry-point/compile-ngc.transform.js:63:13
    at async /home/rieglerm/dev/ngx-ui/node_modules/ng-packagr/lib/graph/transform.js:7:29
```

#### How To Reproduce

Migrating from Angular 12 to 13.3, 
Build worked great before, now it outputs the following error : `TS2318: Cannot find global type 'BigInt'`

#### Version Information

```
ng-packagr:            13.3.0
@angular/compiler:     13.3.0
rollup:                2.70.1
typescript:            4.4.4
node: v14.18.3
npm: 6.14.11
```

I don't even know how to start with this error. There is no instance of `BigInt`.

Fwiw: here is the `ng-package.json` : 

```
{
    "$schema": "node_modules/ng-packagr/ng-package.schema.json",
    "dest": "dist/ngx-ui",
    "assets": [
        "./icons/*.svg",
        "./src/lib/styles.scss"
    ],
    "lib": {
        "entryFile": "src/public-api.ts"
    }
}
```

**Comment by JeanMeche** [comment]
I feel kind a dumb. 

Adding following to my `tsconfig.json` fixed my issue.
```
    "lib": [
      "es2020",
    ]
```
