### ISSUE TITLE
fatal error: too many writes on closed pipe

### ISSUE THREAD

**Issue by atomicrobokid** [ng-packagr/ng-packagr#2361]
## Type of Issue

```
[ x] Bug Report
[ ] Feature Request
```

## Description

Using `ng-packagr` v12.2.7. with Angular v12.2.16, the ng build sporadically fails in out Go pipeline with the below errors:

```
#18 191.2 fatal error: too many writes on closed pipe
#18 191.2 
#18 191.2 goroutine 6 [running]:
#18 191.2 runtime.throw({0x82d33, 0x1e})
#18 191.2 	/usr/local/go/src/runtime/panic.go:1198 +0x7 fp=0x436ec8 sp=0x436ea0 pc=0x12000007
#18 191.2 os.sigpipe()
#18 191.2 	/usr/local/go/src/runtime/os_js.go:143 +0x2 fp=0x436ee0 sp=0x436ec8 pc=0x137c0002
#18 191.2 os.epipecheck(...)
#18 191.2 	/usr/local/go/src/os/file_unix.go:196
#18 191.2 os.(*File).Write(0x40c020, {0x77a000, 0x1e145, 0x20000})
#18 191.2 	/usr/local/go/src/os/file.go:184 +0x25 fp=0x436f68 sp=0x436ee0 pc=0x15b80025
#18 191.2 main.runService.func1(0x42e190, 0x412c00)
#18 191.2 	/Users/evan/dev/esbuild/cmd/esbuild/service.go:70 +0x5 fp=0x436fd0 sp=0x436f68 pc=0x1d580005
#18 191.2 runtime.goexit()
#18 191.2 	/usr/local/go/src/runtime/asm_wasm.s:431 +0x1 fp=0x436fd8 sp=0x436fd0 pc=0x13d10001
#18 191.2 created by main.runService
#18 191.2 	/Users/evan/dev/esbuild/cmd/esbuild/service.go:64 +0xe
#18 191.2 
#18 191.2 goroutine 1 [chan receive]:
#18 191.2 syscall.fsCall({0x763f7, 0x4}, {0x461b60, 0x5, 0x5})
#18 191.2 	/usr/local/go/src/syscall/fs_js.go:521 +0x13
#18 191.2 syscall.Read(0x0, {0x4cc000, 0x4000, 0x4000})
#18 191.2 	/usr/local/go/src/syscall/fs_js.go:389 +0xc
#18 191.2 internal/poll.ignoringEINTRIO(...)
#18 191.2 	/usr/local/go/src/internal/poll/fd_unix.go:582
#18 191.2 internal/poll.(*FD).Read(0x42c060, {0x4cc000, 0x4000, 0x4000})
#18 191.2 	/usr/local/go/src/internal/poll/fd_unix.go:163 +0x4c
#18 191.2 os.(*File).read(...)
#18 191.2 	/usr/local/go/src/os/file_posix.go:32
#18 191.2 os.(*File).Read(0x40c018, {0x4cc000, 0x4000, 0x4000})
#18 191.2 	/usr/local/go/src/os/file.go:119 +0x10
#18 191.2 main.runService(0x1)
#18 191.2 	/Users/evan/dev/esbuild/cmd/esbuild/service.go:101 +0x23
#18 191.2 main.main()
#18 191.2 	/Users/evan/dev/esbuild/cmd/esbuild/main.go:203 +0x8
#18 191.2 
#18 191.2 goroutine 7 [waiting]:
#18 191.2 runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x1)
#18 191.2 	/usr/local/go/src/runtime/proc.go:366 +0x27
#18 191.2 runtime.handleEvent()
#18 191.2 	/usr/local/go/src/runtime/lock_js.go:250 +0x1b
#18 191.2 runtime.goexit()
#18 191.2 	/usr/local/go/src/runtime/asm_wasm.s:431 +0x1
#18 191.2 
#18 191.2 goroutine 8 [chan receive]:
#18 191.2 main.(*serviceType).sendRequest(0x42e190, {0x3ac00, 0x5c8330})
#18 191.2 	/Users/evan/dev/esbuild/cmd/esbuild/service.go:163 +0xd
#18 191.2 main.runService.func2(0x42e190)
#18 191.2 	/Users/evan/dev/esbuild/cmd/esbuild/service.go:92 +0x3
#18 191.2 created by main.runService
#18 191.2 	/Users/evan/dev/esbuild/cmd/esbuild/service.go:89 +0x1e
#18 191.7 
#18 191.7 ———————————————————————————————————————————————
#18 191.7 
#18 191.7 >  NX   ERROR  Running target "app:build" failed
#18 191.7 
#18 191.7   Failed tasks:
#18 191.7   
#18 191.7   - app:build:production
#18 191.7   
#18 191.7   Hint: run the command with --verbose for more details.
#18 191.7 
#18 ERROR: executor failed running [/bin/sh -c npm run build:app:prod]: exit code: 1
```

Triggering a fresh build and it tends to pass

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 12.2.7
@angular/*: 12.2.16
typescript: 4.3.5
rxjs: 6.6.2
node: v14.19.3
npm: 7.5.6
```

**Comment by alan-agius4** [comment]
This is not actionable from our end. Please see: https://github.com/evanw/esbuild/issues/1662

**Comment by Hagay-Reinman** [comment]
It happened to me when the command npm run build-prod --build --prod used all the system memory.
You can see in the file /var/log/syslog
Out of memory: Killed process 188682 (ng build --conf)
Solution increase memory or swapfile
