### ISSUE TITLE
v18.0.0 postcss-configuration exception

### ISSUE THREAD

**Issue by matheo** [ng-packagr/ng-packagr#2854]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I just upgraded Angular v18.0.1 in a Nx monorepo and trying to build a library I got:
```
✖ Compiling with Angular sources in Ivy full compilation mode.

 NX   Cannot read properties of undefined (reading 'has')


TypeError: Cannot read properties of undefined (reading 'has')
    at findFile (node_modules/.pnpm/ng-packagr@18.0.0_@angular+compiler-cli@18.0.0_tslib@2.6.2_typescript@5.4.5/node_modules/ng-packagr/lib/styles/postcss-configuration.js:28:23)
    at loadPostcssConfiguration (node_modules/.pnpm/ng-packagr@18.0.0_@angular+compiler-cli@18.0.0_tslib@2.6.2_typescript@5.4.5/node_modules/ng-packagr/lib/styles/postcss-configuration.js:45:24)
    at StylesheetProcessor.createRenderWorker (node_modules/.pnpm/@nx+angular@19.0.7_@angular-devkit+build-angular@18.0.1_@angular-devkit+core@18.0.1_@angular-_vgsoaa5x42g34xvy5d3ydxwlty/node_modules/@nx/angular/src/executors/utilities/ng-packagr/stylesheet-processor.js:78:36)
    at StylesheetProcessor.process (node_modules/.pnpm/@nx+angular@19.0.7_@angular-devkit+build-angular@18.0.1_@angular-devkit+core@18.0.1_@angular-_vgsoaa5x42g34xvy5d3ydxwlty/node_modules/@nx/angular/src/executors/utilities/ng-packagr/stylesheet-processor.js:51:14)
    at Object.readResource (node_modules/.pnpm/ng-packagr@18.0.0_@angular+compiler-cli@18.0.0_tslib@2.6.2_typescript@5.4.5/node_modules/ng-packagr/lib/ts/cache-compiler-host.js:177:63)
    at AdapterResourceLoader.preload (node_modules/.pnpm/@angular+compiler-cli@18.0.0_@angular+compiler@18.0.0_typescript@5.4.5/node_modules/@angular/compiler-cli/bundles/chunk-D7XZVDL2.js:2559:31)
    at resolveStyleUrl (node_modules/.pnpm/@angular+compiler-cli@18.0.0_@angular+compiler@18.0.0_typescript@5.4.5/node_modules/@angular/compiler-cli/bundles/chunk-LCZH35U2.js:7071:36)
    at node_modules/.pnpm/@angular+compiler-cli@18.0.0_@angular+compiler@18.0.0_typescript@5.4.5/node_modules/@angular/compiler-cli/bundles/chunk-LCZH35U2.js:7099:47
    at Array.map (<anonymous>)
    at ComponentDecoratorHandler.preanalyze (node_modules/.pnpm/@angular+compiler-cli@18.0.0_@angular+compiler@18.0.0_typescript@5.4.5/node_modules/@angular/compiler-cli/bundles/chunk-LCZH35U2.js:7099:29)
```

#### Expected Behaviour

Debugging the trace I logged the input of `findFile` and (with the `@nx/angular:ng-packagr-lite` executor) it seems to receive:
```
{
  searchDirectories: '/absolute/path/to/my/src/frontend/components',
  potentialFiles: [ 'postcss.config.json', '.postcssrc.json' ]
}
```
so destructuring with `const { root, files } of searchDirectories` is resulting in undefined vars.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 18.0.0
@angular/*: 18.0.1
typescript: 5.4.5
rxjs: 7.8.1
node: 18.20.2
pnpm: 8.15.7
```

Thanks in advance @alan-agius4!
Good to see you in the release party

**Comment by diegovilar** [comment]
Same stack version, same problem

**Comment by JoostK** [comment]
This is an NX issue, where they aren't compatible with the changes in #2827.
