### ISSUE TITLE
Not importing files under the same package.json.

### ISSUE THREAD

**Issue by KyleSmith0905** [ng-packagr/ng-packagr#2867]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

_A bug:_ I have two files on the same level as each other, one is for non-angular things, one is for angular things. I can't seem to import the non-angular files from the angular folder.

```
/shared
  /constants
    /date.ts # export const DAYS_IN_WEEK = 7
  /ng
    /components
      /info-panel.ts # import { DAYS_IN_WEEK } from '../../constants/date'
  /angular.json
  /ng-package.json
  /package.json
  /public-api.ts
  /tsconfig.json
```

I receive the following error:
```
✖ Compiling with Angular sources in Ivy full compilation mode.
~\shared\node_modules\.pnpm\rxjs@7.8.1\node_modules\rxjs\dist\cjs\internal\util\reportUnhandledError.js:13
            throw err;
            ^

Error: error TS2688: Cannot find type definition file for 'node'.
  The file is in the program because:
    Entry point of type library 'node' specified in compilerOptions
constants/date.ts:1:1 - error TS6307: File '~/shared/constants/date.ngtypecheck.ts' is not listed within the file list of project '~/shared/tsconfig.json'. Projects must list all files or use an 'include' pattern.

1 export const DAYS_IN_WEEK = 7;
 
ng/components/info-panel.ts:1:1 - error TS6307: File '~/shared/ng/components/info-panel.ngtypecheck.ts' is not listed within the file list of project ~/shared/tsconfig.json'. Projects must list all files or use an 'include' pattern.

1 import { Component } from '@angular/core';
 
ng/components/info-panel.ts:2:30 - error TS6307: File '~/shared/constants/date.ts' is not listed within the file list of project '~/shared/tsconfig.json'. Projects must list all files or use an 'include' pattern.

2 import { DAYS_IN_WEEK } from '../../constants/date';
                               ~~~~~~~~~~~~~~~~~~~~~~
public-api.ts:1:15 - error TS6307: File '~/shared/ng/components/info-panel.ts' is not listed within the file list of project '~/shared/tsconfig.json'. Projects must list all files or use an 'include' pattern.

1 export * from './ng/components/info-panel'
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at compileSourceFiles (~\shared\node_modules\.pnpm\ng-packagr@18.0.0_@angular+compiler-cli@18.0.4_tslib@2.6.3_typescript@5.4.5\node_modules\ng-packagr\lib\ngc\compile-source-files.js:162:15)
    at async ~\shared\node_modules\.pnpm\ng-packagr@18.0.0_@angular+compiler-cli@18.0.4_tslib@2.6.3_typescript@5.4.5\node_modules\ng-packagr\lib\ng-package\entry-point\compile-ngc.transform.js:58:13
    at async ~\shared\node_modules\.pnpm\ng-packagr@18.0.0_@angular+compiler-cli@18.0.4_tslib@2.6.3_typescript@5.4.5\node_modules\ng-packagr\lib\graph\transform.js:6:29

Node.js v18.19.1
 ELIFECYCLE  Command failed with exit code 1.
```

The errors specify that I don't have the files in the "include" pattern, but I do.

#### How To Reproduce

https://github.com/KyleSmith0905/mre--packagr-tsconfig/blob/main/shared/ng-package.json

#### Expected Behaviour

I should be able to import the files since I have included them in my tsconfig (`"include": [...]`)

#### Version Information

```
ng-packagr:            18.0.0
@angular/compiler:     18.0.4
typescript:            5.4.5
```

**Comment by alan-agius4** [comment]
The problem here is that you are using `composite: true` in your tsconfig.json. The Angular compiler does not support this functionality.
