### ISSUE TITLE
Do not know how to serialize a BigInt - ACCESS_POLICY_VIOLATION

### ISSUE THREAD

**Issue by Egor-Koldasov** [ng-packagr/ng-packagr#2930]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

When using Bigint values, for example, during the model creation and the query fails because of the access policy check it fails with the error "Do not know how to serialize a BigInt" instead of showing the policy check error

## Stack trace

```
Error calling enhanced Prisma method `questionnaire.create`: Do not know how to serialize a BigInt
      at ...project_code...) {
    internalStack: 'TypeError: Do not know how to serialize a BigInt\n' +
      '    at JSON.stringify (<anonymous>)\n' +
      '    at module.exports (/Users/egorkolds/code/tenpu-mvp/node_modules/safe-json-stringify/index.js:62:14)\n' +
      '    at formatObject (/Users/egorkolds/code/tenpu-mvp/node_modules/@zenstackhq/runtime/enhancements/utils.js:19:116)\n' +
      '    at PolicyUtil.<anonymous> (/Users/egorkolds/code/tenpu-mvp/node_modules/@zenstackhq/runtime/enhancements/policy/policy-utils.js:696:96)\n' +
      '    at Generator.next (<anonymous>)\n' +
      '    at fulfilled (/Users/egorkolds/code/tenpu-mvp/node_modules/@zenstackhq/runtime/enhancements/policy/policy-utils.js:6:58)
```

#### Version Information

```
"zenstack": "2.3.3",
```

**Comment by alan-agius4** [comment]
@Egor-Koldasov, 

Kindly provide a minimal reproduction

**Comment by alan-agius4** [comment]
Closing as no reproduction was provided.
