### ISSUE TITLE
upgrade to uglify-es

### ISSUE THREAD

**Issue by zealitude** [ng-packagr/ng-packagr#458]
## Type of Issue

```
[ ] Bug Report
[x ] Feature Request
```

## Description
_for features: please describe your use case_

when i run ng-packagr, I got this error

```
BUILD ERROR
Unexpected token operator «*», expected punc «(»
SyntaxError: Unexpected token operator «*», expected punc «(»
    at JS_Parse_Error.get (eval at <anonymous> (C:\wpn-xm\www\project\node_modules\uglify-js\tools\node.js:1:1), <anonymous>:79:23)
    at Object.exports.error (C:\wpn-xm\www\project\node_modules\ng-packagr\lib\util\log.js:8:34)
    at Object.<anonymous> (C:\wpn-xm\www\project\node_modules\ng-packagr\lib\ng-packagr.js:42:17)
    at Generator.throw (<anonymous>)
    at rejected (C:\wpn-xm\www\project\node_modules\ng-packagr\lib\ng-packagr.js:5:65)
```

After investigate, I found that uglify-js does not support ES6 syntax.
By replace the uglify-js to uglify-es, I can build the library successfully.

**Comment by dherges** [comment]
Related to #354

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent ng-packagr.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
