### ISSUE TITLE
A ‘No NgModule metadata found’ error occurs When the package is used in async router .

### ISSUE THREAD

**Issue by AaronJin2013** [ng-packagr/ng-packagr#537]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Try to package a library with NgModule and RouterModule.forChild.
When the app use the library with loadChildren to Async loading，will put a ‘No NgModule metadata found’ error like this.

```bash
ERROR in Error: No NgModule metadata found for 'MyappFeatureModule'.
    at NgModuleResolver.resolve (/Users/aaronjin/aaronjin2013/NX-packagr/node_modules/@angular/compiler/bundles/compiler.umd.js:20249:23)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/aaronjin/aaronjin2013/NX-packagr/node_modules/@angular/compiler/bundles/compiler.umd.js:15218:60)
    at visitLazyRoute (/Users/aaronjin/aaronjin2013/NX-packagr/node_modules/@angular/compiler/bundles/compiler.umd.js:31063:104)
    at visitLazyRoute (/Users/aaronjin/aaronjin2013/NX-packagr/node_modules/@angular/compiler/bundles/compiler.umd.js:31067:17)
    at AotCompiler.listLazyRoutes (/Users/aaronjin/aaronjin2013/NX-packagr/node_modules/@angular/compiler/bundles/compiler.umd.js:31031:20)
    at AngularCompilerProgram.listLazyRoutes (/Users/aaronjin/aaronjin2013/NX-packagr/node_modules/@angular/compiler-cli/src/transformers/program.js:156:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/aaronjin/aaronjin2013/NX-packagr/node_modules/@angular/compiler-cli/src/ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (/Users/aaronjin/aaronjin2013/NX-packagr/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:247:66)
    at Promise.resolve.then.then (/Users/aaronjin/aaronjin2013/NX-packagr/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:561:50)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

#### How To Reproduce

I push the code to this repo
[NX-packagr](https://github.com/AaronJin2013/NX-packagr)

#### Expected Behaviour

I would like to have successful async load routing modules.

#### Version Information

```
ng-packagr: 1.6.0
@angular/*: 5.1.0
typescript: 2.5.3
rxjs: 5.5.2
node: 7.8.0
npm/yarn: 5.6.0
nrwl/nx：0.6.19
ngrx：4.1.1
```

**Comment by banminkyoz** [comment]
I'v faced similar issue
```
ERROR in Error: No NgModule metadata found for 'PhysicalAssetModule'.
    at NgModuleResolver.resolve (/home/kyoz/Desktop/Projects/main-dev/node_modules/@angular/compiler/bundles/compiler.umd.js:20284:23)
    at CompileMetadataResolver.getNgModuleMetadata (/home/kyoz/Desktop/Projects/main-dev/node_modules/@angular/compiler/bundles/compiler.umd.js:15237:60)
    at visitLazyRoute (/home/kyoz/Desktop/Projects/main-dev/node_modules/@angular/compiler/bundles/compiler.umd.js:31175:104)
    at visitLazyRoute (/home/kyoz/Desktop/Projects/main-dev/node_modules/@angular/compiler/bundles/compiler.umd.js:31179:17)
    at AotCompiler.listLazyRoutes (/home/kyoz/Desktop/Projects/main-dev/node_modules/@angular/compiler/bundles/compiler.umd.js:31143:20)
    at AngularCompilerProgram.listLazyRoutes (/home/kyoz/Desktop/Projects/main-dev/node_modules/@angular/compiler-cli/src/transformers/program.js:156:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/kyoz/Desktop/Projects/main-dev/node_modules/@angular/compiler-cli/src/ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (/home/kyoz/Desktop/Projects/main-dev/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:248:66)
    at Promise.resolve.then.then (/home/kyoz/Desktop/Projects/main-dev/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:571:50)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Version:
* angular: 5.2.3
* cli: 1.6.7
* typescript: 2.6.2
* ng-packagr: 2.0.0-rc.10

My **public_api.ts** file:
```
export * from './physical-asset.module';
export * from './components';
```

**Comment by dherges** [comment]
Hi all, I went to reproduce from the github repository you posted.

```bash
$ npm install
$ ls -al node_modules/@nx-ex
ls: node_modules/@nx-ex: No such file or directory
$ ls -al node_modules/nx-example
ls: node_modules/nx-example: No such file or directory
$ cat dist/package.json 
{"name":"nx-example"
$ ng build
/* ... */
ERROR in apps/myapp/src/app/app.module.ts(9,36): error TS2307: Cannot find module '@nx-ex/feature'.
apps/myapp/src/app/app.router.ts(1,36): error TS2307: Cannot find module '@nx-ex/feature'.
```

Would you please check the [nx-packaged demo repository and use a package.json per library](https://github.com/dherges/nx-packaged/blob/master/libs/one-lib/package.json)?

**Comment by AaronJin2013** [comment]
@dherges 
sorry,'@nx-ex/feature' is a file '.nxexample-0.0.1.tgz' in the repository, but clone is not download.

Your 'nx-packaged' demon I have clone and run it, when in local with folder, it's run ok. But when I publish to the nexus, it will put error like this, the error has happened in the past.

```

ERROR in ./apps/one-app/src/app/app.component.ngfactory.js
Module not found: Error: Can't resolve '../../../../node_modules/@nx-test/two-lib/nx-packaged-two-lib.ngfactory' in '/Users/aaronjin/aaronjin2013/nx-packaged/apps/one-app/src/app'
resolve '../../../../node_modules/@nx-test/two-lib/nx-packaged-two-lib.ngfactory' in '/Users/aaronjin/aaronjin2013/nx-packaged/apps/one-app/src/app'
  using description file: /Users/aaronjin/aaronjin2013/nx-packaged/package.json (relative path: ./apps/one-app/src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/aaronjin/aaronjin2013/nx-packaged/package.json (relative path: ./apps/one-app/src/app)
    using description file: /Users/aaronjin/aaronjin2013/nx-packaged/node_modules/@nx-test/two-lib/package.json (relative path: ./nx-packaged-two-lib.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/aaronjin/aaronjin2013/nx-packaged/node_modules/@nx-test/two-lib/nx-packaged-two-lib.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/aaronjin/aaronjin2013/nx-packaged/node_modules/@nx-test/two-lib/nx-packaged-two-lib.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/aaronjin/aaronjin2013/nx-packaged/node_modules/@nx-test/two-lib/nx-packaged-two-lib.ngfactory.js doesn't exist
      as directory
        /Users/aaronjin/aaronjin2013/nx-packaged/node_modules/@nx-test/two-lib/nx-packaged-two-lib.ngfactory doesn't exist
[/Users/aaronjin/aaronjin2013/nx-packaged/node_modules/@nx-test/two-lib/nx-packaged-two-lib.ngfactory]
[/Users/aaronjin/aaronjin2013/nx-packaged/node_modules/@nx-test/two-lib/nx-packaged-two-lib.ngfactory.ts]
[/Users/aaronjin/aaronjin2013/nx-packaged/node_modules/@nx-test/two-lib/nx-packaged-two-lib.ngfactory.js]
[/Users/aaronjin/aaronjin2013/nx-packaged/node_modules/@nx-test/two-lib/nx-packaged-two-lib.ngfactory]
 @ ./apps/one-app/src/app/app.component.ngfactory.js 11:9-91
 @ ./apps/one-app/src/app/app.module.ngfactory.js
 @ ./apps/one-app/src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./apps/one-app/src/main.ts
```

I will try again, thank you for your help.

**Comment by AaronJin2013** [comment]
@dherges 

sorry,'@nx-ex/feature' is a file '.nxexample-0.0.1.tgz' in the repository, but clone is not download.

Maybe my description is not accurate enough. This Error will happen with RouterModule use loadChildren. When you use the async loading and AOT，you will meet it.

**Comment by banminkyoz** [comment]
Sorry for my misunderstanding about ng-packagr. At the moment, this [workaround](https://github.com/angular/angular-cli/issues/6373#issuecomment-319116889) work good with me :smile:
