### ISSUE TITLE
Circular dependencies generated via `flatModuleOutFile`

### ISSUE THREAD

**Issue by dherges** [ng-packagr/ng-packagr#656]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

In `package.json`:

```json
{
  "name": "ngxs",
  "ngPackage": {
    "lib": {
      "entryFile": "src/index.ts"
    }
  }
}
```

The sources contain a file `src/ngx.ts`.

It’s a bug in ng-packagr and/or ngc. What basically happens is:

- ngc generates a `src/ngxs` source file that re-exports symbols from `src/index`.
- `src/index` imports from `src/ngxs` (the original source file)
- During compilation (more precise in `ng.createProgram()`), `src/ngxs` is then resolved to the generated source file rather than the original source file. Since the generated file `src/ngxs` imports from `src/index` and `src/index` imports from `src/ngxs` there is a circular dependency.

Resulting error is:

```bash
BUILD ERROR
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at MetadataBundler.exportAll (/Users/David/Projects/github/amcdnl/ngxs/node_modules/@angular/compiler-cli/src/metadata/bundler.js:71:52)
    at MetadataBundler.exportAll (/Users/David/Projects/github/amcdnl/ngxs/node_modules/@angular/compiler-cli/src/metadata/bundler.js:108:44)
    at MetadataBundler.exportAll (/Users/David/Projects/github/amcdnl/ngxs/node_modules/@angular/compiler-cli/src/metadata/bundler.js:108:44)
    at MetadataBundler.exportAll (/Users/David/Projects/github/amcdnl/ngxs/node_modules/@angular/compiler-cli/src/metadata/bundler.js:108:44)
    at MetadataBundler.exportAll (/Users/David/Projects/github/amcdnl/ngxs/node_modules/@angular/compiler-cli/src/metadata/bundler.js:108:44)
    at MetadataBundler.exportAll (/Users/David/Projects/github/amcdnl/ngxs/node_modules/@angular/compiler-cli/src/metadata/bundler.js:108:44)
    at MetadataBundler.exportAll (/Users/David/Projects/github/amcdnl/ngxs/node_modules/@angular/compiler-cli/src/metadata/bundler.js:108:44)
    at MetadataBundler.exportAll (/Users/David/Projects/github/amcdnl/ngxs/node_modules/@angular/compiler-cli/src/metadata/bundler.js:108:44)
    at MetadataBundler.exportAll (/Users/David/Projects/github/amcdnl/ngxs/node_modules/@angular/compiler-cli/src/metadata/bundler.js:108:44)
    at MetadataBundler.exportAll (/Users/David/Projects/github/amcdnl/ngxs/node_modules/@angular/compiler-cli/src/metadata/bundler.js:108:44)
```

#### How To Reproduce

https://github.com/amcdnl/ngxs

#### Expected Behaviour

Build success 😛 

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            2.1.0
@angular/compiler:     5.2.7
@angular/compiler-cli: 5.2.7
rollup:                0.55.5
tsickle:               0.27.2
typescript:            2.7.2
```

**Comment by dherges** [comment]
Austin says: "I expect that ng-packagr falls back to a file name that doesn't overlap existing source file"

David says: "I expect that ngc gives a better error message"

**Comment by ssameh** [comment]
I had this issue when the file name was sharing the same name of its folder, once I changed file name the issue was resolved
