### ISSUE TITLE
AOT build of application fails when uses re-export in entryComponents

### ISSUE THREAD

**Issue by bukharin** [ng-packagr/ng-packagr#734]
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description

When uses re-export to define entryComponents for NgModule AOT build of end application fails. It seems that `ng-packagr` does not write type infomation to `*metadata.json` files.

#### How To Reproduce

/components/my-component.ts

`
@Component(..) export class MyComponent { }
`

/components/index.ts:

```
export {MyComponent} from "./my-component";
```

/module.ts:

```
import {MyComponent} from "./components";
@NgModule({
  ...
  entryComponents: [
    // entry here
    MyComponent
  ]
})
export class MyModule {}
```

Angular compilier fail to build application that uses library. If I use direct import in the module, like `import {MyComponent} from "./components/my-component"`, error is gone.

Angular compilier error:

```
ERROR in TypeError: Cannot read property 'members' of undefined
    at AotSummaryResolver.resolveSummary (C:\Git\stream-webapp\node_modules\@angular\compiler\bundles\compiler.umd.js:32817:56)
    at CompileMetadataResolver._loadSummary (C:\Git\stream-webapp\node_modules\@angular\compiler\bundles\compiler.umd.js:14837:66)
    at CompileMetadataResolver._getEntryComponentMetadata (C:\Git\stream-webapp\node_modules\@angular\compiler\bundles\compiler.umd.js:15895:66)
    at C:\Git\stream-webapp\node_modules\@angular\compiler\bundles\compiler.umd.js:15361:55
    at Array.map (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (C:\Git\stream-webapp\node_modules\@angular\compiler\bundles\compiler.umd.js:15361:18)
    at C:\Git\stream-webapp\node_modules\@angular\compiler\bundles\compiler.umd.js:31325:70
    at Array.forEach (<anonymous>)
    at analyzeFile (C:\Git\stream-webapp\node_modules\@angular\compiler\bundles\compiler.umd.js:31308:53)
    at AotCompiler._analyzeFile (C:\Git\stream-webapp\node_modules\@angular\compiler\bundles\compiler.umd.js:30510:17)
    at AotCompiler.findGeneratedFileNames (C:\Git\stream-webapp\node_modules\@angular\compiler\bundles\compiler.umd.js:30526:42)
    at Object.findGeneratedFileNames (C:\Git\stream-webapp\packages\compiler-cli\src\transformers\program.ts:434:60)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getSourceFile (C:\Git\stream-webapp\packages\compiler-cli\src\transformers\compiler_host.ts:384:45)
    at findSourceFile (C:\Git\stream-webapp\node_modules\typescript\lib\typescript.js:73056:29)
    at processImportedModules (C:\Git\stream-webapp\node_modules\typescript\lib\typescript.js:73228:25)
    at findSourceFile (C:\Git\stream-webapp\node_modules\typescript\lib\typescript.js:73104:17)
    at args (C:\Git\stream-webapp\node_modules\typescript\lib\typescript.js:72993:85)
    at getSourceFileFromReferenceWorker (C:\Git\stream-webapp\node_modules\typescript\lib\typescript.js:72966:34)
    at processSourceFile (C:\Git\stream-webapp\node_modules\typescript\lib\typescript.js:72993:13)
    at processRootFile (C:\Git\stream-webapp\node_modules\typescript\lib\typescript.js:72848:13)
    at C:\Git\stream-webapp\node_modules\typescript\lib\typescript.js:72006:60
    at Object.forEach (C:\Git\stream-webapp\node_modules\typescript\lib\typescript.js:1526:30)
    at Object.createProgram (C:\Git\stream-webapp\node_modules\typescript\lib\typescript.js:72006:16)
    at AngularCompilerProgram._createProgramWithBasicStubs (C:\Git\stream-webapp\packages\compiler-cli\src\transformers\program.ts:482:27)
    at C:\Git\stream-webapp\packages\compiler-cli\src\transformers\program.ts:182:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3

```

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 2.4.1
@angular/*: 5.2.3
typescript: 2.6.2
rxjs: 5.5.6
node: 9.8.0
npm/yarn: 5.7.1
```

**Comment by bukharin** [comment]
@alan-agius4 sure.

I found this promblem not only for entryComponents, but for all imports from re-export modules (like index.ts).

When I use direct import like `import {MyComponent} from "./components/my-component/my-component.ts"` - metadata.json file contains metadata required for angular compilier-cli.

I try to describe the difference of created metadata.json files:

`my-module.metadata.json`:

```json
{
  "metadata": {
    "MyModule": {
      "__symbolic": "class",
      "decorators": [
        {
          // ...
          "arguments": [
            {
              // decorator parameters
              "entryComponents": [
                {
                  "__symbolic": "reference",
                  "name": "ɵi"
                }
                // other components
              ]
            }
          ]
        }
      ]
      // ...
    },
    // metadata for ɵi reference
    "ɵi": {
      "__symbolic": "class",
      "decorators": [
        // ...
      ],
      "members": {
        // ...
      }
    }
  }
}
```

But when I has import like `import {MyComponent} from "./components"` metadata.json file looks like:

``` json
{
  "metadata": {
    "MyModule": {
      "__symbolic": "class",
      "decorators": [
        {
          // ...
          "arguments": [
            {
              // decorator parameters
              "entryComponents": [
                {
                  "__symbolic": "reference",
                  "name": "ɵi"
                }
                // other components
              ]
            }
          ]
        }
      ]
      // ...
    },
    // no metadata for ɵi reference
  }
}
```

During AOT compilier does not receive any information of used type and throw exception above

**Comment by MurhafSousli** [comment]
It was working in Angular 5, when I upgraded my library to Angular 6, I got the same issue

My library module looks like this:
```ts
import { ImageItemComponent } from './templates/image-item.component';
import { VideoItemComponent } from './templates/video-item.component';
import { IframeItemComponent } from './templates/iframe-item.component';
import { ThumbnailItemComponent } from './templates/thumbnail-item.component';

const ENTRY_COMPONENTS = [
    ImageItemComponent,
    VideoItemComponent,
    IframeItemComponent,
    ThumbnailItemComponent
];

@NgModule({
  imports: [
    // ...
  ],
  declarations: [
    // ...
    ...ENTRY_COMPONENTS
  ],
  exports: [
    // ...
  ],
  entryComponents: [
    ...ENTRY_COMPONENTS
  ]
})
export class GalleryModule { }
```

When I build in the app in AOT I get the following errors:

`
ERROR in : Cannot determine the module for class ImageItemComponent in  'PATH_TO_COMPONENT' Add ImageItemComponent to the NgModule to fix it.`

`Cannot determine the module for class VideoItemComponent in  'PATH_TO_COMPONENT' Add VideoItemComponent to the NgModule to fix it.`

`Cannot determine the module for class IframeItemComponent in  'PATH_TO_COMPONENT' Add IframeItemComponent to the NgModule to fix it.`

`Cannot determine the module for class ThumbnailItemComponent in 'PATH_TO_COMPONENT' Add ThumbnailItemComponent to the NgModule to fix it.
`

I even tried to add `ENTRY_COMPONENTS` to the `exports` property, but it did not work.

It only worked when I import them in `AppModule`

**Comment by mlc-mlapis** [comment]
@MurhafSousli ... did you used the same but without spread syntax? So ...
```
entryComponents: [
    ENTRY_COMPONENTS
  ]
```

**Comment by MurhafSousli** [comment]
@mlc-mlapis No, in my actual code, I add each component
```ts
@NgModule({
  declarations: [
    ImageItemComponent,
    VideoItemComponent,
    IframeItemComponent,
    ThumbnailItemComponent
  ],
  entryComponents: [
    ImageItemComponent,
    VideoItemComponent,
    IframeItemComponent,
    ThumbnailItemComponent
  ]
})
```

**Comment by xino1010** [comment]
@bukharin did you resolve the problem?

**Comment by silentFred** [comment]
Anything happened here? sitting with the same issue where I'm trying to expose a re-export

**Comment by frankdavidcorona** [comment]
I think that the problem it's related with the use of Barrier Strategy, I got the same issue trying to use a library made by myself inside another application. Just remove the use of Barrier to export components of the library and the error is gone on build my main application with the library inside.

**Comment by benwinding** [comment]
Barrel files are the problem in my case...

index.ts = :-1:

**Comment by Kharl** [comment]
I used export default class for component
`export default class ConfirmComponent {`
and import  
`import ConfirmComponent from '@shared/components/confirm/confirm.component';`
`@NgModule({
  declarations: [
    ....
    ConfirmComponent,
  ],
  exports: [
    ...
    ConfirmComponent,
  ],
  entryComponents: [ConfirmComponent]
})`
replace on named export for component
`export class ConfirmComponent {`
and `import { ConfirmComponent } from '@shared/components/confirm/confirm.component';`
It helped me (Angular 8)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes.
