### ISSUE TITLE
BUILD_ ERROR : Path must be a string. Received undefined

### ISSUE THREAD

**Issue by acarboni71** [ng-packagr/ng-packagr#883]
## Type of Issue

Got an error when building a library

```
[ x ] Bug Report
[ ] Feature Request
```

## Description

I have a library, in which a sub-module (gui/form) references another sub-module (gui/panel). When I try ti build (npm run pack) I get this:

BUILD ERROR
Path must be a string. Received undefined
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.dirname (path.js:1349:5)
    at Object.<anonymous> (/my/work/foundation/git/angular-toolkit/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:32:72)
    at Generator.next (<anonymous>)
    at /my/work/foundation/git/angular-toolkit/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/my/work/foundation/git/angular-toolkit/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:3:12)
    at exports.compileNgcTransform.transform_1.transformFromPromise (/my/work/foundation/git/angular-toolkit/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:16:75)
    at SwitchMapSubscriber.pipe_1.pipe.operators_1.switchMap.graph [as project] (/my/work/foundation/git/angular-toolkit/node_modules/ng-packagr/lib/brocc/transform.js:8:29)
    at SwitchMapSubscriber._next (/my/work/foundation/git/angular-toolkit/node_modules/rxjs/operators/switchMap.js:90:27)

To avoid this error, just remove the dependency. Inside gui/form/module.ts, remove:

import { PanelModule as TkPanelModule} from "@hpe/toolkit/gui/panel";

together with the corresponding line inside the "imports" section.

Please, note that sub-module dependency is already used and works. For example, "gui/panel" module depends on both "directive" and "service" modules. The difference here, between "gui/form" and "gui/panel"  is  that the imported module (gui/panel) contains html code. 

#### How To Reproduce

unpack the attached tgz, go inside its dir and issue these commands:
   npm install
   cd src
   npm install
   cd ..
   npm run pack

You will get a build error

#### Expected Behaviour

Library successfully built without errors

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 2.4.5
@angular/*: 5.2.10
typescript: 2.6.2
rxjs: 5.5.5 (this is anyway not declared in the outside package.json)
node: 8.10.0
npm/yarn: x.y.z (not used
[project.zip](https://github.com/dherges/ng-packagr/files/2017048/project.zip)

)
```

**Comment by KErez** [comment]
@acarboni71 Did you solve this issue?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent version.
